### ISSUE TITLE
Exponential backoff for channel reconnect

### ISSUE THREAD

**Issue by jeffweiss** [phoenixframework/phoenix#793] opened 2015-04-22 09:46 UTC
@chrismccord said during the ElixirConf EU tutorial that he needed to open an issue for timeout exponential backoff when channels can't connect.

**Comment by burgalon** [comment] 2015-12-15 18:55
@chrismccord It seems rejoinUntilConnected() (in actions/phoenix.js) is responsible on rejoining channels however there is no socket reconnect code? Does this rely on passing a `transport` option in the constructor of something like https://github.com/joewalnes/reconnecting-websocket ?

**Comment by chrismccord** [comment] 2015-12-15 19:05
> @chrismccord It seems rejoinUntilConnected() (in actions/phoenix.js) is responsible on rejoining channels however there is no socket reconnect code in case the socket closes? 
Does this rely on passing a transport option in the constructor of something like reconnecting-websocket ?

The expo backoff code applies to both the socket connection and the channel recovery, so something like the reconnecting-websocket is not necessary, we take care of it.

**Comment by burgalon** [comment] 2015-12-15 19:26
in actions/phoenix.js - rejoin timer calls rejoinUntilConnected() which calls this.rejoinTimer.setTimeout() every time again, making sure that the reconnection timer keeps trying again and again.
However, for the socket reconnectTimer, we only call `disconnect(() => connect())` with no this.reconnectTimer.setTimeout() which should make sure that it keeps trying to reconnect, and so the timer only kicks in once.

Here's the relevant code from phoenix.js

    this.reconnectTimer       = new Timer(() => {
      this.disconnect(() => this.connect())
    }, this.reconnectAfterMs)

...

    this.rejoinTimer  = new Timer(
      () => this.rejoinUntilConnected(),
      this.socket.reconnectAfterMs
    )

...
  rejoinUntilConnected(){
    this.rejoinTimer.setTimeout()
    if(this.socket.isConnected()){
      this.rejoin()
    }
  }

**Comment by burgalon** [comment] 2015-12-15 19:34
This seems to fix it
```javascript
this.reconnectTimer       = new Timer(() => {
      console.log('reconnect timer')
      if(!this.isConnected()) {
        console.log('disconnecting => connect')
        !this.disconnect(() => this.connect())
        this.reconnectTimer.setTimeout()
      }
    }, this.reconnectAfterMs)
```

Would love to make a first PR

**Comment by chrismccord** [comment] 2015-12-15 19:37
We call setTimeout here https://github.com/phoenixframework/phoenix/blob/master/web/static/js/phoenix.js#L454

Which is called when the socket connection fails, which restarts the connect timer sequence. Can you verify that this is a reproducible bug? I'm not seeing it with the code as is.

**Comment by burgalon** [comment] 2015-12-15 19:38
indeed the timer kicks the first time, but then it stops and never kicks in again.

**Comment by burgalon** [comment] 2015-12-15 19:45
Also wondering, doesn't it make sense that if the initial call to connect() fails, shouldn't it reconnect as well as if it disconnected?

**Comment by chrismccord** [comment] 2015-12-15 19:56
@burgalon I cannot recreate this. Attached is a gif showing the backoff working as expected. Can you confirm?

![](https://s3.amazonaws.com/f.cl.ly/items/3L2y1F060Y1F2t0L1A2U/Screen%20Recording%202015-12-15%20at%2002.54%20PM.gif?v=6271db2c)
http://cl.ly/141A2F2L1f14

**Comment by chrismccord** [comment] 2015-12-15 20:01
> Also wondering, doesn't it make sense that if the initial call to connect() fails, shouldn't it reconnect as well as if it disconnected?

Yes, which is what happens when the onClose callback is fired, which should always be fired if the connection open fails. If it doesn't, it's indeed a bug, but I'm not seeing it yet :)

**Comment by burgalon** [comment] 2015-12-15 20:09
The ticks you're seeing are for the channel rejoins... the reconnect never happens

**Comment by burgalon** [comment] 2015-12-15 20:12
Try doing console.log inside phonex.js
```javascript
    this.reconnectTimer       = new Timer(() => {
      console.log('reconnect')
      !this.disconnect(() => this.connect())
    }, this.reconnectAfterMs)
```

**Comment by chrismccord** [comment] 2015-12-15 20:13
In the gif, the client definitely rejoins. I took another recording, removed all channel joining, and add a socket.onOpen hook to demonstrate:

![](https://s3.amazonaws.com/f.cl.ly/items/2n0a1U161K3T0a1e3f43/Screen%20Recording%202015-12-15%20at%2003.11%20PM.gif?v=79c5e1ac)

**Comment by chrismccord** [comment] 2015-12-15 20:36
> Try doing console.log inside phonex.js

Same deal. To loop others in, this seems to be an issue with react-native and their WebSocket polypill not firing onClose events on failed connections

**Comment by burgalon** [comment] 2015-12-16 05:54
Yep.... That's a react-native issue. There's already a pending pull request https://github.com/facebook/react-native/pull/3229/files

**Comment by burgalon** [comment] 2015-12-16 06:42
I guess we can close this issue here

**Comment by chrismccord** [comment] 2015-12-16 14:44
Thanks for verifying!

**Closed by chrismccord** 2015-12-16 14:44 UTC
