### ISSUE TITLE
got "compile dependency :cowboy" when   mix ecto.create 

### ISSUE THREAD

**Issue by googya** [phoenixframework/phoenix#1323] opened 2015-10-29 16:29 UTC
Fetch and install dependencies? [Yn] Y
* running npm install && node node_modules/brunch/bin/brunch build
* running mix deps.get

We are all set! Run your Phoenix application:

    $ cd hello_phoenix
    $ mix ecto.create
    $ mix phoenix.server

You can also run your app inside IEx (Interactive Elixir) as:

    $ iex -S mix phoenix.server

➜  demos  cd hello_phoenix
➜  hello_phoenix  mix ecto.create
==> fs (compile)
Compiled src/sys/fsevents.erl
Compiled src/sys/inotifywait_win32.erl
Compiled src/sys/inotifywait.erl
Compiled src/fs_event_bridge.erl
Compiled src/fs_app.erl
Compiled src/fs_sup.erl
Compiled src/fs_server.erl
Compiled src/fs.erl
==> ranch (compile)
Compiled src/ranch_transport.erl
Compiled src/ranch_sup.erl
Compiled src/ranch_server.erl
Compiled src/ranch_protocol.erl
Compiled src/ranch_listener_sup.erl
Compiled src/ranch_tcp.erl
Compiled src/ranch_conns_sup.erl
Compiled src/ranch_ssl.erl
Compiled src/ranch_app.erl
Compiled src/ranch_acceptor.erl
Compiled src/ranch_acceptors_sup.erl
Compiled src/ranch.erl
==> poolboy (compile)
Compiled src/poolboy_worker.erl
Compiled src/poolboy_sup.erl
Compiled src/poolboy.erl
==> decimal
Compiled lib/decimal.ex
Generated decimal app
==> poison
Compiled lib/poison.ex
Compiled lib/poison/parser.ex
Compiled lib/poison/decoder.ex
Compiled lib/poison/encoder.ex
Generated poison app
==> cowlib (compile)
Compiled src/cow_qs.erl
Compiled src/cow_spdy.erl
Compiled src/cow_multipart.erl
Compiled src/cow_http_te.erl
Compiled src/cow_http_hd.erl
Compiled src/cow_date.erl
Compiled src/cow_cookie.erl
Compiled src/cow_http.erl
Compiled src/cow_mimetypes.erl
WARN:  Expected /Users/leslie/快盘/Programming/elixir/demos/hello_phoenix/_build/dev/lib/cowlib to be an app dir (containing ebin/*.app), but no .app found.
WARN:  Expected /Users/leslie/快盘/Programming/elixir/demos/hello_phoenix/_build/dev/lib/ranch to be an app dir (containing ebin/*.app), but no .app found.
==> cowboy (compile)
WARN:  Expected /Users/leslie/快盘/Programming/elixir/demos/hello_phoenix/_build/dev/lib/cowlib to be an app dir (containing ebin/*.app), but no .app found.
WARN:  Expected /Users/leslie/快盘/Programming/elixir/demos/hello_phoenix/_build/dev/lib/ranch to be an app dir (containing ebin/*.app), but no .app found.
Dependency not available: cowlib-.* ({git,
                                      "https://github.com/ninenines/cowlib.git",
                                      "1.0.0"})
Dependency not available: ranch-.* ({git,
                                     "https://github.com/ninenines/ranch.git",
                                     "1.0.0"})
Uncaught error in rebar_core: {'EXIT',
                               {badarg,
                                [{io,format,
                                  [standard_error,
                                   "ERROR: ~p failed while processing ~s: ~s\n",
                                   [compile,
                                    [47,85,115,101,114,115,47,108,101,115,108,
                                     105,101,47,24555,30424,47,80,114,111,103,
                                     114,97,109,109,105,110,103,47,101,108,
                                     105,120,105,114,47,100,101,109,111,115,
                                     47,104,101,108,108,111,95,112,104,111,
                                     101,110,105,120,47,100,101,112,115,47,99,
                                     111,119,98,111,121],
                                    "rebar_abort"]],
                                  []},
                                 {rebar_utils,abort,2,[]},
                                 {rebar_core,maybe_execute,8,[]},
                                 {rebar_core,process_dir1,7,[]},
                                 {rebar_core,process_commands,2,[]},
                                 {rebar,main,1,[]},
                                 {escript,run,2,
                                  [{file,"escript.erl"},{line,757}]},
                                 {escript,start,1,
                                  [{file,"escript.erl"},{line,277}]}]}}
==> hello_phoenix
** (Mix) Could not compile dependency :cowboy, "/Users/leslie/.mix/rebar" command failed. You can recompile this dependency with "mix deps.compile cowboy", update it with "mix deps.update cowboy" or clean it with "mix deps.clean cowboy"

**Comment by josevalim** [comment] 2015-10-29 16:53
I think it is your Erlang version. Which one are you using?

**Comment by googya** [comment] 2015-10-29 17:15
@josevalim  

➜  ~  brew install erlang
Warning: erlang-18.1 already installed

**Comment by chrismccord** [comment] 2015-10-29 17:21
Just to make sure we know what erl version you are using, what does `$ erl` report?

**Comment by googya** [comment] 2015-10-30 01:33
@chrismccord  
➜  ~  erl
Erlang/OTP 18 [erts-7.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Eshell V7.1  (abort with ^G)
1>

**Comment by josevalim** [comment] 2015-10-30 01:35
Ok, so it can only be rebar. What does `which rebar` return? If it is something global, can you uninstall it and install the one with `mix local.rebar`?

**Comment by googya** [comment] 2015-10-30 01:40
There is no global rebar,

```shell
➜  hello_phoenix  which rebar
rebar not found

cd ~/.mix
archives	rebar
```

**Comment by josevalim** [comment] 2015-10-30 12:20
Sorry, I have no idea why this is happening. Can we try one last thing? In the error message we have some chinese characters, what if you try to create a project outside of your `/Users/NAME`? Try something in /etc or any other directory. If it works, the issue is printing UTF-8 characters. :)

**Comment by josevalim** [comment] 2015-10-30 13:35
@googya I am so sorry, this is a bug in Elixir. As I suspected, the issue is in the non-latin characters in your path name. You can move the project to another path. However, It is fixed in master and v1.1 branches. Therefore, you can also fix it by compiling Elixir from source. It is straight-forward and we have instructions for it here: http://elixir-lang.org/install.html

**Comment by googya** [comment] 2015-11-02 01:53
@josevalim  I see, thank you

**Closed** 2015-11-02 03:12 UTC

**Comment by tslater** [comment] 2016-04-20 05:01
@josevalim I am having the same issue, but with normal characters. In my case, I have a symbolic link. I wonder if that was the original issue here. I'm running my code mounted readonly. I'm symbolically linking  _build, deps, and mix.lock. I get this:

```
/var/phoenix # mix phoenix.server
==> idna (compile)
==> mimerl (compile)
==> ranch (compile)
==> ssl_verify_fun (compile)
==> certifi (compile)
WARN:  Missing plugins: [pc]
==> esqlite (compile)
==> fs (compile)
==> metrics (compile)
==> cowlib (compile)
WARN:  Expected /var/phoenix/_build/dev/lib/cowlib to be an app dir (containing ebin/*.app), but no .app found.
WARN:  Expected /var/phoenix/_build/dev/lib/ranch to be an app dir (containing ebin/*.app), but no .app found.
==> cowboy (compile)
WARN:  Expected /var/phoenix/_build/dev/lib/cowlib to be an app dir (containing ebin/*.app), but no .app found.
WARN:  Expected /var/phoenix/_build/dev/lib/ranch to be an app dir (containing ebin/*.app), but no .app found.
Dependency not available: cowlib-.* ({git,
                                      "https://github.com/ninenines/cowlib.git",
                                      "1.0.0"})
Dependency not available: ranch-.* ({git,
                                     "https://github.com/ninenines/ranch.git",
                                     "1.0.0"})
ERROR: compile failed while processing /var/deps/cowboy: rebar_abort
** (Mix) Could not compile dependency :cowboy, "/root/.mix/rebar compile skip_deps=true deps_dir="/var/phoenix/_build/dev/lib"" command failed. You can recompile this dependency with "mix deps.compile cowboy", update it with "mix deps.update cowboy" or clean it with "mix deps.clean cowboy"
```
Do you think symbolic links are my issue? I'd like to configure a different place to put these writeable files, if possible.

**Comment by josevalim** [comment] 2016-04-20 07:37
> Do you think symbolic links are my issue?

Please try without symbolic links and let us know. :)

If you want to change those, you can configure mix.lock (:lockfile), deps (:deps_path) and _build (:build_path) directories in your mix.exs. Elixir v1.2 is required.

**Comment by tslater** [comment] 2016-04-20 12:33
I had my symbolic links as relative and they were breaking. Now I have them as absolute and it seems to be working just fine. Also, thanks for letting me know about those settings. That's exactly what I was looking for!
