### ISSUE TITLE
phoenix.js error in IE11

### ISSUE THREAD

**Issue by ivanovv** [phoenixframework/phoenix#3965] opened 2020-08-21 21:34 UTC
### Environment

* Phoenix version: 1.5.4

### Expected behavior
Works fine with IE11.

### Actual behavior
IE11 throws an exception: “Object doesn't support property or method 'find'”

Commit that has introduced that exception: https://github.com/phoenixframework/phoenix/commit/8b0d39058ca19a3a55249f6392eb940e22047380

The line is 
```js
let dupChannel = this.channels.find(c => c.topic === topic && (c.isJoined() || c.isJoining()))
```

**Comment by jamesmacfie** [comment] 2020-08-26 02:28
`find` isn't supported in IE11 as per https://caniuse.com/#feat=array-find

MDN has a polyfill for this that you could add to your site or else there's probably some on NPM. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find

**Comment by ivanovv** [comment] 2020-08-26 16:50
Looking at the discussions in several PRs it is clear that we at least tried to support IE11. 

Dropping the support is a braking change.

@chrismccord thoughts?

**Comment by featherart** [comment] 2020-09-04 21:50
Looks like Array.prototype.filter would work. https://caniuse.com/#search=Array.prototype.filter()

`filter()` returns an array whereas `find()` returns the first match. This should do it. Happy to submit a PR.

`let dupChannel = this.channels.filter(c => c.topic === topic && (c.isJoined() || c.isJoining())).shift()`

**Comment by levistovall** [comment] 2020-10-26 13:45
Is any particular sequence of steps necessary to reproduce this issue?

**Comment by bcardarella** [comment] 2021-06-25 01:23
@chrismccord can this be closed with `wontfix` now that IE11 support is being dropped?

I think for those that want to support legacy browsers they can add Babel to their webpack config with the proper rules to polyfill for modern JS.

**Closed** 2021-06-25 14:58 UTC
