### ISSUE TITLE
error spinning up server

### ISSUE THREAD

**Issue by jbhatab** [phoenixframework/phoenix#1949] opened 2016-09-28 20:07 UTC
### Environment

* Elixir version (elixir -v): 1.3.3
* Phoenix version (mix deps): 1.2.1
* NodeJS version (node -v): 6.3
* NPM version (npm -v): 3.8.3
* Operating system: Mac elcaptain 10.11.6

### Expected behavior
Spin up server using iex -S mix phoenix.server

Got error and prompted to run mix local.hex

ran mix local.hex

I've done this before just fine
### Actual behavior
It errors out with mix local.hex and mix local.hex --force

![screen shot 2016-09-28 at 1 07 32 pm](https://cloud.githubusercontent.com/assets/2458718/18930351/8f67f934-857c-11e6-9892-51bd3a41d77f.png)

**Comment by chrismccord** [comment] 2016-09-28 20:15
Please see this SO answer as it looks like your issue:
http://stackoverflow.com/a/35173096

If you continue to have problems, please bump this thread and we'll point you in the right direction, but I"m closing since this is not phoenix related. Thanks!

**Closed by chrismccord** 2016-09-28 20:15 UTC

**Comment by jbhatab** [comment] 2016-09-28 20:18
@chrismccord tried that and it didn't work. I'm thinking this has to do with an auto prompt I got to upgrade to erlang 19.1 and it caused some sort of issue on my machine. I'll manage to google through it most likely but not the best if an auto erlang prompt causes this kind of break

**Comment by chrismccord** [comment] 2016-09-28 20:21
How did you install erlang? The issue is your erlang was not baked with ssl. You could try reinstalling a different way, such as using brew, or kerl

**Comment by chrismccord** [comment] 2016-09-28 20:21
Sounds like the Erlang solutions package, so I would recommend trying brew or kerl

**Comment by fregas** [comment] 2019-02-08 20:24
https://stackoverflow.com/questions/35170911/mix-deps-get-failed-seems-missing-ssl/54599662#54599662

See my answer (fregas) on this one.
