### ISSUE TITLE
Repo.update returns :ok but does not write anything

### ISSUE THREAD

**Issue by manoadamro** [phoenixframework/phoenix#4399] opened 2021-08-05 13:01 UTC
Using this code:

```
    IO.puts("about to update...")
    case task |> Task.changeset(%{status_id: status.id, assignee_id: assignee_id}) |> Repo.update() do
      {:ok, task} ->
        IO.puts("THERE WAS NO ERROR")
        IO.inspect(task)
        {:noreply, socket}
      {:error, changeset} ->
        IO.puts("THERE WAS AN ERROR")
        IO.inspect(changeset)
        {:noreply, socket}
    end
```

I get:
```
about to update...
THERE WAS NO ERROR
```
(plus a big, unchanged task object)

but the database was never written to.
I have also tried using the generated method:
```
  @doc """
  Updates a task.

  ## Examples

      iex> update_task(task, %{field: new_value})
      {:ok, %Task{}}

      iex> update_task(task, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_task(%Task{} = task, attrs) do
    task
    |> Task.changeset(attrs)
    |> Repo.update()
  end
```

with exactly the same result.

### Environment

* Elixir version (elixir -v): 1.12.2
* Phoenix version (mix deps):  1.5.9
* Node.js version (node -v): 15.8.0
* Operating system: 10.15.7

### Expected behavior

Calling an "update" function should either update, or return an error. 
It shouldn't return ok but not write anything

### Actual behavior

returns ok but does not write to the database

**Comment by rmoorman** [comment] 2021-08-05 13:29
@manoadamro , maybe a silly question but does `task |> Task.changeset(%{status_id: status.id, assignee_id: assignee_id})` actually return changes?
Would it be possible for you to either insert change the line
```
    case task |> Task.changeset(%{status_id: status.id, assignee_id: assignee_id}) |> Repo.update() do
```
to read
```
    case task |> Task.changeset(%{status_id: status.id, assignee_id: assignee_id}) |> IO.inspect() |> Repo.update() do
```
and give share the output
OR even share some more code so that we would be able to reproduce this behaviour? Maybe some example repo containing just the output of generating a new Phoenix project and the code that triggers the wrong behaviour could also shed more light on this.

**Comment by manoadamro** [comment] 2021-08-05 13:39
@rmoorman you're right, it's not generating any changes. then changeset was indeed empty (although I'm not really sure why)

running in IEx to check:
```
iex(14)> Task.changeset(Task, %{status_id: 1, assignee_id: 1})
** (FunctionClauseError) no function clause matching in Ecto.Changeset.cast/4    
    
    The following arguments were given to Ecto.Changeset.cast/4:
    
        # 1
        Codepilot.Tasks.Task
    
        # 2
        %{assignee_id: 1, status_id: 1}
    
        # 3
        [:confidence, :uplift, :status_id, :assignee_id]
    
        # 4
        []
    
    Attempted function clauses (showing 5 out of 5):
    
        def cast(_data, %{__struct__: _} = params, _permitted, _opts)
        def cast({data, types}, params, permitted, opts) when is_map(data)
        def cast(%Ecto.Changeset{types: nil}, _params, _permitted, _opts)
        def cast(%Ecto.Changeset{changes: changes, data: data, types: types, empty_values: empty_values} = changeset, params, permitted, opts)
        def cast(%{__struct__: module} = data, params, permitted, opts)
    
    (ecto 3.6.2) lib/ecto/changeset.ex:468: Ecto.Changeset.cast/4
    (codepilot 0.1.0) lib/codepilot/tasks/task.ex:23: Codepilot.Tasks.Task.changeset/2
iex(14)> 
```

Changing:
```
    case task |> Task.changeset(%{status_id: status.id, assignee_id: assignee_id}) |> IO.inspect() |> Repo.update() do
```

To:
```
case Task.changeset(task, %{status_id: status.id, assignee_id: assignee_id}) |> IO.inspect() |> Repo.update() do
```

has fixed it (although I'm not sure why)

**Comment by rmoorman** [comment] 2021-08-05 19:24
Well the error you got in IEx was due to using the Task module as an argument to the changeset function instead of passing a struct based on that module (`Task` vs `%Task{}`).

As for the change you made, I am also not sure why that change would have worked for you 😄 
Anyway, I am glad if I can be of any help.

If you have some more code to reproduce the issue, please share! And in case the problem is solved, please let us know/close the issue.

**Comment by manoadamro** [comment] 2021-08-05 19:29
Yeah, I’m convinced I’ve messed something up somewhere along the line. 
thanks again :)

**Closed** 2021-08-05 19:29 UTC
