### ISSUE TITLE
scrub_params on :new action, causes phoenix to throw 400 without error message

### ISSUE THREAD

**Issue by praveenperera** [phoenixframework/phoenix#2484] opened 2017-09-08 21:31 UTC
### Environment

* Elixir  1.5.1:
* Phoenix 1.2.4:
* Operating system: macOS 10.12.6

So today I was silly and instead of doing `plug :scrub_params, "report" when action in [:create]` in the controller I did `plug :scrub_params, "report"`. Which caused the server to throw a 400 error without any error messages, when going to the new report path. Just `[info] Sent 400 in 2ms`

I was wondering if this would be a good opportunity to improve error messages. I was able to figure it out eventually but I was very confused and getting frustrated. I could see this being a place a newbie might get tripped up.

**Comment by chrismccord** [comment] 2017-09-13 20:41
We could add a Logger.debug to report the expected param was missing. Can you send a PR? Thanks!

**Comment by josevalim** [comment] 2017-09-13 21:08
@chrismccord we should probably raise an exception and use plug status to have it rendered as 400. This way we get the proper debug pages in development and everything as well as the proper status on prod.

**Comment by praveenperera** [comment] 2017-09-13 21:19
@chrismccord I'd love to be able to contribute back to phoenix, but I like @josevalim idea of raising and exception, since the debug messages can be easy to miss.

**Comment by chrismccord** [comment] 2017-09-14 05:02
On further inspect, it looks like this is what we are already doing today :)
https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/exceptions.ex#L18-L32

@praveenperera in dev, you should get a helpful error page, but in other env's not using   `debug_errors: true`, the exception would be translated to 400. Were you in dev mode when you got the 400's with no error page?

**Comment by michalmuskala** [comment] 2017-09-14 05:28
I wonder if maybe sending any error using the `Plug.Exception` protocol should be a bit more verbose. I think any error should at least leave some trace in the logs.

**Comment by josevalim** [comment] 2017-09-14 09:35
That's what we did but it generated complaints. Maybe we should use level debug instead of error.

**Comment by praveenperera** [comment] 2017-09-14 11:30
@chrismccord I doubled checked I am in dev, and I do get the error if I POST without my required param ("report"). 

But my mistake was different. I forgot to add the guard clause to only run the plug on create. 

So I had

```
plug :scrub_params, "report"
```

Instead of

```
plug :scrub_params, "report" when action in [:create]
```

And when I went to the "new" I got a 400 ("Internal server error") without any messages. 

Here is the log I get

```
[info] GET /admin/reports
[debug] QUERY OK source="users" db=0.9ms
SELECT u0."id", u0."name", u0."email", u0."admin", u0."inserted_at", u0."updated_at" FROM "users" AS u0 WHERE (u0."id" = $1) [2]
[debug] Processing by Madison.CMS.ReportController.new/2
  Parameters: %{}
  Pipelines: [:browser, :protected, :cms]
[info] Sent 400 in 1ms
```

Sorry about new clearer earlier.

**Comment by chrismccord** [comment] 2017-09-14 15:46
Right, but your `plug :scrub_params, "report"` should have raised MissingParamError and shown the debug error page when visiting /new . Let me see if I can recreate what your are seeing

**Comment by praveenperera** [comment] 2017-09-14 17:22
@chrismccord not sure if you saw the update, but it only raises if i changed the `defexception [:message, plug_status: 400]` to ` defexception [:message, plug_status: 500]`. I don't know if that helps.

**Comment by josevalim** [comment] 2018-02-12 20:25
Duplicate of #2687.

**Closed by josevalim** 2018-02-12 20:25 UTC
