### ISSUE TITLE
Channel is closed when payload is too big

### ISSUE THREAD

**Issue by narrowtux** [phoenixframework/phoenix#1873] opened 2016-08-16 10:38 UTC
When I send large payloads via `Phoenix.Channel.push` I get an `:ok` but after that, it will close the channel with an error but does not print anything as to why the channel was closed.

The payload size limitation might be an issue with Poison or the maximum frame size of the WebSocket protocol, but Phoenix should at least raise or return something else than `:ok` when this happens.

### Environment

* Elixir version (elixir -v): 1.3.1
* Phoenix version (mix deps): 1.2.0
* NodeJS version (node -v): 6.2.0
* NPM version (npm -v): 3.8.9
* Operating system: OS X 10.11.3 (15D21)

**Comment by josevalim** [comment] 2016-08-16 11:03
@narrowtux can you provide a simple app that reproduces the issue as well as a the browser you are using? This would help us a lot as we won't have to put efforts on reproducing the issue.

**Comment by narrowtux** [comment] 2016-08-16 11:08
OK, you’ll have a demo app at the end of the day probably. 

BTW, I was using node.js as the “Browser”, using the official phoenix channel javascript client (with a hack to make it work with the node.js websocket).

**Comment by narrowtux** [comment] 2016-08-16 11:52
Ok, so writing that test case it turned out that when I send that data to the browser it's actually no problem. Only if the receiving end is node.js it will call `channel.onError` with `undefined` as error.

I'll send you an email with the zip of the test case since it contains data I'd not like the whole world to see. Is that alright @josevalim ?

**Comment by chrismccord** [comment] 2016-08-16 11:55
the onError callbacks are called if the connection closes for any unclean reason, including problems on the client. So can we rule out this isn't an issue on the node.js websocket client's end? If the browser is accepting the payload, my hunch is the browser's WebSocket is handling the payload, but the nodejs shim is not

**Comment by narrowtux** [comment] 2016-08-16 11:56
Hmm so this is probably clearly out of scope of the phoenix project right?

**Comment by chrismccord** [comment] 2016-08-16 12:07
We don't have to abandon efforts immediately, but my hunch is the node.js end :) Is there anything on the node's websocket client side that allows logging? You could also try hacking your `deps/phoenix/lib/phoenix/endpoint/cowboy_websocket.ex` and log the exit codes/reasons in the `websocket_terminate` clauses to see if the client is ending a specific close code.

**Comment by narrowtux** [comment] 2016-08-16 12:23
I managed to enable logging on the websocket library(theturtle32/WebSocket-Node).

It looks like the fault is really at the websocket library, since it prints out `frame too large` (why ever)

```
sendUTF: 69 bytes
fragmentAndSend
sendFrame
handleSocketResume: socket resume event
processReceivedData
-- insufficient data for frame
handleSocketData
socket data
setKeepaliveTimer
processReceivedData
processFrame
 -- frame: Opcode: 1, fin: true, length: 97, hasPayload: true, masked: false
-- Text Frame
---- Emitting 'message' event
Received 97 characters.
joined
handleSocketData
socket data
setKeepaliveTimer
processReceivedData
-- frame too large
drop
Forcefully dropping connection. skipCloseFrame: undefined, code: 1009, description: Frame size of 2268751 bytes exceeds maximum accepted frame size
sendCloseFrame state: open, reasonCode: 1009, description: Frame size of 2268751 bytes exceeds maximum accepted frame size
sendFrame
clearCloseTimer
Emitting WebSocketConnection close event
undefined
Drop: destroying socket
handleSocketClose: received socket close
clearCloseTimer
```

**Comment by narrowtux** [comment] 2016-08-16 12:26
This suggests that the payload is not fragmented on Phoenix' end.

**Comment by josevalim** [comment] 2016-08-16 12:37
@narrowtux Or a bug on node.js side. :) Also there are different websockets protocols and maybe node.js and the browser are using different ones, and one of them is broken on the Phoenix side. At this point, I would continue investigating and not rule out anything.

**Comment by narrowtux** [comment] 2016-08-16 12:39
Yeah I agree that it's a bug in the node.js library, as a maximum fragment size is not specified in the WebSocket standard.

I just noted that Phoenix apparently does not fragment large frames.

**Comment by josevalim** [comment] 2016-08-23 13:46
I am closing this since I don't believe this is a bug. If we are somewhat required to fragment large frames, please include a link to the relevant parts in the specs and let us know!

**Closed by josevalim** 2016-08-23 13:46 UTC

**Comment by narrowtux** [comment] 2016-08-24 14:48
That's fine, I haven't read this in the spec myself, it's just that the javascript library is a bit overzealous. Thanks for assisting my debugging session though ;)
