### ISSUE TITLE
Don't swallow exceptions when they are translated with Plug.Exception protocol

### ISSUE THREAD

**Issue by michalmuskala** [phoenixframework/phoenix#2687] opened 2017-12-20 20:08 UTC
### Environment

* Elixir version (elixir -v): 1.5.2
* Phoenix version (mix deps): 1.3.0
* Operating system: macOS

### Actual behavior

In production, when running with `debug_errors: false` when one of the errors that implement the `Plug. Exception` protocol is raised, nothing is logged - only the status code is changed.
Unfortunately that means we're throwing away a lot of information that could be helpful for the programmer when trying to debug production issues.

For example, in couple places we use `Repo.insert!` when data inserted doesn't come from the user (so there's no point in rendering errors from the changeset). The result is that in the logs we can only see a sudden `rollback` query and that `Send 422 in Xms`. Basically nothing to go on (tracing is a god-send).

### Expected behavior

There should be at least some trace of the exception in the logs. I agree, it's sensible not to log it with `error` level (since in many cases exceptions like that are used for normal application operation, however unfortunate I think that might be). But I think logging with `warn` or at least `debug` should always occur. If not by default, there should at least be a way to configure it.

**Comment by josevalim** [comment] 2017-12-20 20:27
The issue is that we skip the logging in Plug's `Logger.Translator` for Cowboy. Unfortunately we cannot change the level during the translator so I am not quite sure how to tackle this. We could add logging in render errors for non-500 but it feels we would be leaking concerns all over the place.

**Comment by josevalim** [comment] 2018-01-16 12:35
Similar issue was reported on Phoenix.Ecto: https://github.com/phoenixframework/phoenix_ecto/issues/74

**Comment by josevalim** [comment] 2018-02-12 23:36
@michalmuskala I think we should log something everytime we trigger "render errors" with at least the exception name (and the template to be rendered). We can also log the stacktrace and full error message using `debug`... but I don't think that would be useful to most since they will be likely running on at least `info`?

**Comment by michalmuskala** [comment] 2018-02-14 12:06
I think even debug would be better than nothing. Switching on debug logging would be first step when I try to debug strange things. But maybe it should be configurable somehow? I'm not sure.

**Comment by idi-ot** [comment] 2018-02-19 19:37
Does the stack trace still get generated in these cases? And if it does, can it affect app performance significantly?

Besides showing the generated stacktrace for exceptions intercepted by `Plug.Exception`, could there be an option to disable stacktrace collection?

**Comment by michalmuskala** [comment] 2018-02-20 10:50
I don't think the cost of building the stacktrace would be significant here. Yes, it is an expensive operation, but its cost is tiny compared to any networking operation. Did you measure it's a problem for your application?

**Comment by idi-ot** [comment] 2018-02-20 10:52
> Did you measure it's a problem for your application?

Not yet ...

**Comment by idi-ot** [comment] 2018-02-20 14:29
So I've tried to setup a benchmark like the one I've described above and the results are

When raising
```sh
> wrk -t30 -c40 -d10s -s guest.lua http://localhost:4000/r
Running 10s test @ http://localhost:4000/r
  30 threads and 40 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    18.88ms    9.76ms  93.67ms   77.19%
    Req/Sec    47.52     14.68   100.00     66.93%
  14341 requests in 10.08s, 3.56MB read
  Socket errors: connect 0, read 14334, write 0, timeout 0
  Non-2xx or 3xx responses: 14341
Requests/sec:   1423.25
Transfer/sec:    361.37KB
```

When not raising
```sh
wrk -t30 -c40 -d10s -s admin.lua http://localhost:4000/r
Running 10s test @ http://localhost:4000/r
  30 threads and 40 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     6.09ms    6.79ms  90.01ms   87.39%
    Req/Sec   197.50     70.69   610.00     73.77%
  59259 requests in 10.05s, 13.57MB read
Requests/sec:   5894.82
Transfer/sec:      1.35MB
```

**Comment by josevalim** [comment] 2018-02-20 14:36
@idi-ot when you raise in Cowboy 1.0, the connection is considered corrupted and a new one has to be started. So the cost you are seeing is very likely because of the reconnects, which is shown in the socket errors, and not because of the raising.

So you are benchmarking something very different from being discussed here, because we are not discussing if we should raise or not, but rather if we should log when something has been already raised.

Such drastic results are going to show up only on benchmarks like above since browsers and APIs most likely have a pool of connections and the failure to success ratio is not going to be 0/100.

Note Cowboy 2.0 multiplexes each request in a separate process, so this cost shouldn't be there.

**Comment by idi-ot** [comment] 2018-02-20 14:37
@josevalim 

> when you raise in Cowboy 1.0, the connection is considered corrupted and a new one has to be started.

Is it also true for `Ecto.NotFound` exceptions?

**Comment by josevalim** [comment] 2018-02-20 14:42
> Is it also true for Ecto.NoResultsError exceptions?

Any exception, yes. But again, you are not supposing to be hitting those, they are exceptions. :)

**Comment by idi-ot** [comment] 2018-02-20 14:43
They are getting hit in a default phoenix project (`Repo.get!()`)

**Comment by josevalim** [comment] 2018-02-20 14:48
> They are getting hit in a default phoenix project with some generated context (Repo.get!(ContextName, id)).

Why are people accessing a wrong ID? On a normal use of your application, it is *not* going to happen unless there is a bug or the user manually fiddles with the URL. Again, it is supposed to happen only exceptionally.

**Comment by josevalim** [comment] 2018-06-10 20:37
Closing in favor of #2865.

**Closed by josevalim** 2018-06-10 20:37 UTC
