### ISSUE TITLE
Issue when installing js client

### ISSUE THREAD

**Issue by LostKobrakai** [phoenixframework/phoenix#3445] opened 2019-06-12 12:39 UTC
### Environment

* Elixir version (elixir -v):
* Phoenix version (mix deps):
* NodeJS version (node -v): 11.10.0
* NPM version (npm -v): 6.9.0
* Operating system:

### Expected behavior

Proper installation of phoenix via npm.

### Actual behavior

The js file is installed into `node_modules/phoenix/js/phoenix.js` while the `package.json` includes: `"main": "./priv/static/phoenix.js"`, which does not exist. The only installed folders are `/js` and `/test` with 4 test scripts.

**Comment by dmarkow** [comment] 2019-06-12 15:01
Confirmed on phoenix@1.4.7. Webpack errors out now:

```
Module not found: Error: Can't resolve 'phoenix'
```

Reverting to 1.4.6 now fixes it.

**Comment by chrismccord** [comment] 2019-06-12 15:54
@LostKobrakai to be clear, is this happening on a fresh app with our `file:` based npm dep, or only if referencing phoenix as a npm dep from npm?

**Comment by dmarkow** [comment] 2019-06-12 16:02
@chrismccord At least for me, this is referencing phoenix@1.4.7 from npm (not the `file:` dep) -- our frontend app is completely separate from our backend phoenix app.

Viewing the package on unpkg.com shows the same issue:

- https://unpkg.com/phoenix@1.4.7 gives an error
- https://unpkg.com/phoenix@1.4.7/package.json shows the ./priv/static/phoenix.js path for "main"
- https://unpkg.com/phoenix@1.4.7/js/phoenix.js shows the actual file at ./js/phoenix

**Comment by dmarkow** [comment] 2019-06-12 16:04
It actually looks like the package didn't get compiled for 1.4.7, so the original source got published instead of the compiled code

**Comment by LostKobrakai** [comment] 2019-06-12 16:08
@dmarkow is correct. I meant when installing from npm.

**Comment by LostKobrakai** [comment] 2019-06-12 16:10
> https://unpkg.com/phoenix@1.4.7 gives an error

Add a `/` to the end to show the folder instead of being redirected to the entrypoint.
https://unpkg.com/phoenix@1.4.7/

**Comment by chrismccord** [comment] 2019-06-12 16:10
Fixed with phoenix@1.4.8 . Thanks!

**Closed by chrismccord** 2019-06-12 16:10 UTC
