### ISSUE TITLE
Phoenix rest api performance problem

### ISSUE THREAD

**Issue by Sachinx0e** [phoenixframework/phoenix#1544] opened 2016-02-13 04:28 UTC
I have been testing Phoenix for a rest api. I have built a very basic application that has one model "User" with fields "FullName", "Email", "Address", "PhoneNo".  
When I tested the server with Apache jmeter, the performance of the server degraded sharply when it reached 1500 concurrent users. The test included getting all the users from the database repeatedly. The database has 7 user records. The through put never seems to go above 3000 req/sec and as soon as the throughput reaches 1200 req/sec, the error rate starts to go up. The errors are "connection refused" and "connection timed out". 
I even built a similar application in Golang using beego framework and it went upto 6900 req/sec with no errors at all. 

The link to phoenix project : https://github.com/Sachinx0e/test_phoenix.git

Apache Jmeter config
Number of threads : 5000
Ramp-Up period    : 100
Loop Count            : 100

**Comment by josevalim** [comment] 2016-02-13 08:26
How are you starting your application to run your benchmarks? Are you running them in production?

**Comment by Sachinx0e** [comment] 2016-02-13 09:11
mix compile.protocols
elixir --sname node1 --cookie secret_token -pa _build/prod/consolidated -S mix phoenix.server

**Comment by josevalim** [comment] 2016-02-13 10:42
The command above does not look like you are running in production. Are you setting MIX_ENV? If so, can you paste the full commands? What is your Elixir version>?

**Comment by Sachinx0e** [comment] 2016-02-13 12:46
Yes I have set MIX_ENV to prod. I am running on windows 10.

**Comment by josevalim** [comment] 2016-02-13 13:21
Can you please let us know your Elixir version as asked previously? Also, can you please copy the information printed just after the server is started (with environment and port you are currently running)? Also, what is the pool size set in your `config/prod.secret.exs` file?

I have just tried the project locally and I got 8000req/s and it behaved fine with more concurrent connections. Also please check if increasing the size of the database pool in your "config/prod.secret.exs" will yield better performance.

**Comment by Sachinx0e** [comment] 2016-02-13 15:45
The Elixir version is 1.2.1 and Erlang OTP is 18 [erts- 7.1].
The information just after server is started.
`21:13:13.241 [info] Running Test.Endpoint with Cowboy using http on port 4001`

My pool size is 20. I tried changing pool size but it had no noticeable difference.

**Comment by josevalim** [comment] 2016-02-13 15:56
Thank you! Indeed something seems to not be working as desired, it is probably something Windows specific. Btw, you need longer need to pass -pa _build/prod/consolidated in Elixir 1.2.1

**Comment by Sachinx0e** [comment] 2016-02-13 15:58
Yes I suppose it's something windows specific. I am getting the environment ready on ubuntu now. I will test it on ubuntu and get back with the results.

**Comment by josevalim** [comment] 2016-02-13 16:05
Thank you!

You don't need to explicitly compile protocols nor pass -pa _build/prod/consolidated, yes. This should be enough:

```elixir
$ mix compile
$ elixir --sname node1 --cookie secret_token -S mix phoenix.server
```

**Comment by Sachinx0e** [comment] 2016-02-13 18:53
I just tested it on my Linux box(Ubuntu 8 cores, 16 GB ram) The results are same. The through put goes down sharply after 3000 r/s and 1200 concurrent users and error rate goes up.
The commands I used to start the server where
`MIX_ENV=prod mix compile.protocols`
`MIX_ENV=prod PORT=4001 elixir -S mix phoenix.server`

**Comment by chrismccord** [comment] 2016-02-13 19:23
please try increasing the db pool size and report back. Thanks!

**Comment by chrismccord** [comment] 2016-02-13 20:20
@Sachinx0e to be clear, please try increasing the pool size on your linux box and see if it makes a difference. I know we didn't see an improvement on the windows side when we tried this, but let's verify on linux as well.

**Comment by josevalim** [comment] 2016-02-13 20:21
Given I still cannot reproduce the issue (it performs well here), I would also suggest using other benchmark tools and see if we can reproduce the behaviour. I will give JMeter a try but consider using something like `wrk` or `siege` for benchmark.

**Comment by Sachinx0e** [comment] 2016-02-14 09:01
@chrismccord Yes I increased the pool size from 20 -> 40 -> 60 -> 80. The results where the same.
@josevalim I tried with wrk `wrk -t10 -c5000 -d120s -H 'Host: example.com' --timeout 20s http://192.168.1.9:4001/api/users/`


Results for elixir/phoenix

| stats   | Avg   | Stdev    | Max   | +/- Stdev |
|---------|-------|----------|-------|-----------|
| Latency | 1.23s | 165.02ms | 5.05s | 97.36%    |
| Req/Sec | 95.83 | 84.86    | 650   | 72.45%    |

**108409 requests in 2.00m,   138.85MB read**
Socket errors: connect 0, read 941, write 0, timeout 0

**Requests/Sec     :   902.66**
Transfer/Sec       :   1.16 MB

Results for golang/beego

| stats   | Avg    | Stdev    | Max    | +/- Stdev |
|---------|--------|----------|--------|-----------|
| Latency | 1.91s  | 665.15ms | 17.50s | 87.76%    |
| Req/Sec | 232.98 | 124.79   | 1.83k  | 68.02%    |

**271785 requests in 2.00m, 235.09MB read**
Socket errors: connect 0, read 274, write 0, timeout 80

**Requests/sec    :   2263.35**
Transfer/sec     :    1.96 MB

**Comment by josevalim** [comment] 2016-02-14 09:12
@Sachinx0e I have run the same tests here and the results are fine:

```
$ wrk -t10 -c5000 -d120s -H 'Host: example.com' --timeout 20s  http://localhost:4001
Running 2m test @ http://localhost:4001
  10 threads and 5000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   325.38ms  660.07ms  13.67s    98.01%
    Req/Sec   393.54    247.44     2.39k    70.27%
  406619 requests in 2.00m, 0.86GB read
  Socket errors: connect 151, read 10087, write 0, timeout 0
Requests/sec:   3385.68
Transfer/sec:      7.33MB
```

However, there is an important question here: does beego *log requests by default*? Because Phoenix logs by default and that does reduce throughput considerably. If beego does not log, you may consider setting the following in your config/prod.exs to be a more apples to apples comparison:

    config :logger, level: :error

**Comment by josevalim** [comment] 2016-02-14 09:13
And this is the database configuration I used in my tests:

```elixir
# Configure your database
config :test, Test.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "postgres",
  database: "test_prod",
  pool_size: 20
```

**Comment by Sachinx0e** [comment] 2016-02-14 09:15
Yes Beego logs request by default. I have disabled the request logging in both the apps. Even I am using the same config. I have set the pool_size to 40.

**Comment by josevalim** [comment] 2016-02-14 09:25
Ok, I was finally able to reproduce the error you are getting. We definitely have requests timing out when waiting for the database. I will increase timeout values and see how it will perform.

**Comment by Sachinx0e** [comment] 2016-02-14 09:34
Thanks a lot :) Do you want me to give you the binary for my golang server ? Just for running the benchmarks.

**Comment by josevalim** [comment] 2016-02-14 09:37
Bad and good news!

Unfortunately Ecto 1.1 does not allow us to customize the pool timeout but Ecto 2.0 (soon to be released) does. By adding the following dependencies:

```elixir
{:postgrex, github: "elixir-lang/postgrex"},
{:ecto, github: "elixir-lang/ecto", override: true},
```

And the following configuration:

```elixir
config :test, Test.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "postgres",
  database: "test_prod",
  hostname: "localhost",
  pool_size: 40,
  timeout: 60_000,
  pool_timeout: 60_000
```

I went from the following results:

```
$ wrk -t10 -c5000 -d120s -H 'Host: example.com' --timeout 20s  http://localhost:4001/api/users
Running 2m test @ http://localhost:4001/api/users
  10 threads and 5000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   893.13ms  484.05ms  17.00s    69.32%
    Req/Sec   118.58    109.65     0.88k    80.70%
  87528 requests in 2.00m, 60.90MB read
  Socket errors: connect 151, read 7545, write 44, timeout 129
  Non-2xx or 3xx responses: 668
Requests/sec:    728.84
Transfer/sec:    519.32KB
```

To the following:

```
$ wrk -t10 -c5000 -d120s -H 'Host: example.com' --timeout 20s  http://localhost:4001/api/users
Running 2m test @ http://localhost:4001/api/users
  10 threads and 5000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   402.95ms    1.06s   19.98s    98.39%
    Req/Sec   352.56    129.03     2.36k    79.87%
  363246 requests in 2.00m, 253.98MB read
  Socket errors: connect 151, read 11011, write 3, timeout 34
Requests/sec:   3024.39
Transfer/sec:      2.11MB
```

You still have some timeouts but that's a trade-off you will *have* to make. You can surely make users wait more than 1 minute for a request but I would say timing out at this point would be much better.

**Comment by josevalim** [comment] 2016-02-14 09:43
Actually, I was wrong. pool_timeout does work on Ecto 1.1, I forgot to recompile after changing it. :D So you don't need to change your dependencies, just add timeout and pool_timeout to your repo configuration and you should be fine:

```elixir
config :test, Test.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "postgres",
  database: "test_prod",
  pool_size: 40,
  timeout: 60_000,
  pool_timeout: 60_000
```

I will edit this post with actual results soon.

**Comment by Sachinx0e** [comment] 2016-02-14 09:46
Thanks a lot :) Testing it right now

**Comment by fishcakez** [comment] 2016-02-14 17:00
I got this with some config changes and Ecto 2.0:
```
Running 2m test @ http://127.0.0.1:4001/api/users/
  10 threads and 5000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   179.43ms  359.65ms  15.21s    99.82%
    Req/Sec     1.21k     1.01k    4.31k    71.29%
  719380 requests in 2.00m, 709.51MB read
  Socket errors: connect 3989, read 0, write 0, timeout 0
Requests/sec:   5989.89
Transfer/sec:      5.91MB
```
I always get 3989 connect errors no matter the duration so don't want to post misleading information, maybe @josevalim can ping me again on IRC - you had left before I saw you link me to this issue.

**Comment by josevalim** [comment] 2016-02-14 18:12
@fishcakez just post them here, it is best for @Sachinx0e to try on his/her machine anyway for an apples to apples comparison.

**Comment by fishcakez** [comment] 2016-02-14 18:38
```elixir
use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with brunch.io to recompile .js and .css sources.
config :test, Test.Endpoint,
  http: [port: 4001,
    protocol_options: [max_keepalive: :infinity],
    backlog: 8096],
  debug_errors: false,
  code_reloader: false,
  check_origin: false

config :logger, level: :error
config :logger, compile_time_purge_level: :error

# Configure your database
config :test, Test.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "postgres",
  database: "phoenix_test_dev",
  hostname: "localhost",
  log: false,
  pool_size: 10
```
```
Running 2m test @ http://127.0.0.1:4001/api/users/
  10 threads and 5000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   170.89ms   19.04ms 603.74ms   91.43%
    Req/Sec   645.66    447.95     2.94k    63.89%
  699215 requests in 2.00m, 689.50MB read
  Socket errors: connect 3989, read 0, write 0, timeout 0
Requests/sec:   5822.00
Transfer/sec:      5.74MB
```

**Comment by josevalim** [comment] 2016-02-14 19:44
@Sachinx0e it is so weird you got a smaller improvement than I did. Just as note, don't do the same mistake as I did, always remember to run `MIX_ENV=prod mix compile` after changing your configs. In any case, I am closing this. I believe we got to the root cause, it is just a shame you can't reproduce the same results as us. Thank you.

**Closed by josevalim** 2016-02-14 19:44 UTC
