### ISSUE TITLE
Explicit reconnect doesn't rejoin channels

### ISSUE THREAD

**Issue by indrekj** [phoenixframework/phoenix#3458] opened 2019-07-02 09:01 UTC
* Phoenix version: 1.4.8

### Expected behavior

Explicit reconnect should rejoin the channels.

### Actual behavior

Doing an explicit reconnect on existing open connection using:
```
socket.disconnect()
socket.connect()
```

or
```
socket.reconnectTimer.scheduleTimeout()
```

does not rejoin the channels. Instead we start getting `reason: "unmatched topic"` errors.

We use this to try to switch from LongPoll connection to WebSocket connection.

Basically what we do is (coffeescript):
```
  startAvoidLongPollWorker = (socket) ->
    work = ->
      # Avoid changing transports and interfering with the reconnection logic
      # when we don't have an established connection and the reconnection might
      # already be in progress
      return if socket.connectionState() != 'open'

      # Return if the user is already not using LongPoll
      return if socket.transport != Phoenix.LongPoll

      newTransport = findNewTransport(socket.transport)

      # Return if the new transport is the same
      return if socket.transport == newTransport

      # Change socket transport and schedule a reconnect
      socket.transport = newTransport
      socket.reconnectTimer.scheduleTimeout()

    setInterval(work, AVOID_LONGPOLL_WORKER_INTERVAL_IN_MS)
```

As a workaround we currently did:
```
    socket.onOpen ->
      # Do channel rejoin in next event loop, otherwise it's too soon and
      # doesn't work.
      channels = socket.channels
      setTimeout(->
        channels.forEach((channel) ->
          channel.rejoinTimer.scheduleTimeout()
        )
      )
```

**Comment by chrismccord** [comment] 2019-07-03 02:21
`socket.reconnectTimer.scheduleTimeout()` these are private APIs so to avoid confusion, can you confirm if the following alone triggers this issue:

```
socket.disconnect()
socket.connect()
```

Do things rejoin in this case?

**Comment by indrekj** [comment] 2019-07-03 07:10
They don't. The result is same. There's no rejoin and I start getting `unmatched topic` errors.

**Comment by snewcomer** [comment] 2020-01-06 04:42
@indrekj Based on your knowledge, is this still a current bug and do you think this should be fixed by the library (and not userland code)?  If so, I can startg taking a look...

**Comment by chrismccord** [comment] 2020-01-07 20:31
@snewcomer definitely something we should handle on our side. Channels rejoins happen automatically on connection recovery, but sounds like there is a bug here when disconnect => reconnect in the same event loop. Can you take a look? Thanks!

**Comment by snewcomer** [comment] 2020-02-06 05:45
https://github.com/phoenixframework/phoenix/pull/3665/files#r375649649

Hi @indrekj.  My comment about `onConnClose` eventually being called only applies to the test context.  So, in a non-test environment, it would be great to hear what happens if you `connect` in the next macroTask...

```js
socket.disconnect();
setTimeout(() => {
  socket.connect();
}, 100);
```

Is "onConnClose" eventually called (w/ master or your latest version of phoenix)?

**Comment by indrekj** [comment] 2020-02-06 08:56
> Is "onConnClose" eventually called

It is not.

**Comment by snewcomer** [comment] 2020-02-06 15:49
👍 Seeing the same thing in a running app.

Although, I'm unable to reproduce `reason: "unmatched topic" `calling `disconnect` and `connect` sequentially in a very simple case.  I hate to ask b/c you have put in a bunch of great work, but is this something you can provide in a demo app?

**Comment by snewcomer** [comment] 2020-04-04 21:37
@indrekj I think we have it fixed! Would love to hear what you think about #3708!!

## Before
![Screen Shot 2020-04-04 at 2 26 55 PM](https://user-images.githubusercontent.com/7374640/78461721-5f00c980-7680-11ea-9aab-ace5d0710e7d.png)

<img width="443" alt="Screen Shot 2020-04-04 at 2 28 37 PM" src="https://user-images.githubusercontent.com/7374640/78461887-ab98d480-7681-11ea-802c-276c7c9f9cd4.png">


## After
![Screen Shot 2020-04-04 at 2 22 33 PM](https://user-images.githubusercontent.com/7374640/78461703-295be080-7680-11ea-8fbf-310364a12231.png)

<img width="426" alt="Screen Shot 2020-04-04 at 2 35 43 PM" src="https://user-images.githubusercontent.com/7374640/78461883-9de34f00-7681-11ea-9be7-c8ef615da8e5.png">

**Closed** 2020-04-16 04:14 UTC
Labels: kind:bug
