### ISSUE TITLE
phoenix.js odd timeout behavior

### ISSUE THREAD

**Issue by ghalle** [phoenixframework/phoenix#2035] opened 2016-12-15 22:29 UTC
### Environment

* Elixir version (elixir -v): 1.4.0-rc.1
* Phoenix version (mix deps): 1.2.1
* NodeJS version (node -v): 7.2.0
* NPM version (npm -v): 3.10.9
* Operating system: Windows 10 Pro 64 bits

# First behavior
1. Join a channel
2. Wait for the timeout to happen
3. Connect the socket

### Expected behavior
One channel join request is sent to the server
### Actual behavior
Two join requests are sent to the server, the reply to the first one is ignored because it timed-out before it was even sent

# Second behavior
1. Put a Process.sleep(5000) on the join callback of the channel
2. Join the channel
3. Wait 6 secs
4. Connect the socket

### Expected behavior
One channel join request is sent to the server
### Actual behavior
Multiple join requests are sent and some are sent with a ref value of null as seen on the screenshot below:
http://i.imgur.com/7QSRd76.png

# Repoducible Example
Reproducible demo of the second behavior: https://github.com/ghalle/bugdemo
To test the first one, comment out the Process.sleep and increase the setTimeout to 12 seconds

# Investigation
The first behavior happens because the `startTimeout` is called as soon as the `join` is called rather than when it is actually sent through the socket, I suggest `startTimeout` only be called when the message is actually sent through the socket

The issue with the ref being null seems to be caused by `startTimeout` returning early because a `timeoutTimer` already exists, since the ref is set inside `startTimeout` the message is being sent with a null ref.

UPDATE: Dug a little deeper and found out that this is caused by the rejoinTimer calling `rejoinUntilConnected` faster than the timeout of `startTimeout`. The default values for the `reconnectAfterMs` function used by the rejoinTimer are `[1000, 2000, 5000, 10000]` while the default join timeout is `10000` so if it takes a few secs for the server to reply to the join, the client will try to rejoin again before there is a reply or before it times out

**Comment by rossta** [comment] 2016-12-28 11:34
Thanks for this report. 

I was able to reproduce these issues while writing tests for #2047. I have failing tests in [another branch](https://github.com/rossta/phoenix/compare/6703d3f7...698777a) that I can try to address in followup PR. The crux of the problem is the interaction of the [timeout timer](https://github.com/phoenixframework/phoenix/blob/0aaea792a46084735726c3893b7609da5baf1f65/web/static/js/phoenix.js#L269) and [rejoin timer](https://github.com/phoenixframework/phoenix/blob/0aaea792a46084735726c3893b7609da5baf1f65/web/static/js/phoenix.js#L294), which can lead to multiple overlapping join requests and then race conditions with steps like @ghalle has described.

**Comment by rossta** [comment] 2016-12-28 18:39
After thinking about it a bit more, it's worth asking whether or not the first behavior is "as designed". One could argue that the timeout to join a channel should start when the join function is called, instead of when the socket actually sends the request to the server. 

Perhaps a change in the `socket.connect()` API would make this a moot point. It could be written to take a callback or return a Promise that ensures a successful connection before attempting to interact with channels:

```javascript
socket.connect().then(() => {
  channel.join()
})
```

**Comment by chrismccord** [comment] 2017-01-04 03:54
I would love to avoid a promise-based api in general until it would no longer require shims. Pre 1.0, we also used a callback approach to do the same thing:

    socket.connect(() => channel.join() ...)

But we decided to use the current approach once we moved to the join/receive chains where callers individually handle their lifecycle events of both the socket and channels. So we should fix this race condition without changing the API. @rossta will you be able to take this on? Thanks!

**Comment by rossta** [comment] 2017-01-04 04:47
@chrismccord Yes, I can give it a shot. It may help to have tests provided by #2047 - could you provide feedback on that PR when you get a chance? Thanks!

**Comment by chrismccord** [comment] 2017-05-28 01:57
It's a non-starter if IE11 isn't supported, but even when it is I'm not convinced a promise-based api is the way to go. The only way to handle timeout or error cases is an catch and if checks everywhere, which isn't great. Additionally, folks can easily promisify the existing api if they please, so it's not something I plan to rewrite anytime soon. Thanks for the heads up!

**Comment by MikaAK** [comment] 2017-05-29 02:08
I agree totally that promises aren't the right solution for something like this. I would consider something along the lines of observables maybe for the future. You can implement using the official spec should you not want to make use of existing libs https://github.com/tc39/proposal observable. That way it can still interop with other observables. As it is we can use bindCallback in rxjs so it's not a bug deal bit it's a pleasant solution to the websocket/async problem in this case

**Comment by rossta** [comment] 2017-06-02 13:15
FWIW I have a fix (#2115) for the reported issues here without any changes to API.

**Comment by chrismccord** [comment] 2017-07-18 18:15
@rossta thanks! This should be fixed on master.

**Closed by chrismccord** 2017-07-18 18:15 UTC
Labels: kind:bug
