### ISSUE TITLE
Running `mix gettext.extract` on a new project without Ecto throws an error

### ISSUE THREAD

**Issue by nicolashery** [phoenixframework/phoenix#1547] opened 2016-02-14 20:52 UTC
## Reproduce

1. Create a new project `mix phoenix.new test_gettext --no-ecto`
1. In the project directory, run `mix gettext.extract`

Notice the error:

```
Compiled web/web.ex
Compiled lib/test_gettext.ex
Compiled web/channels/user_socket.ex
Compiled web/views/error_helpers.ex
Compiled web/gettext.ex
Compiled web/views/error_view.ex
Compiled web/views/page_view.ex
Compiled web/router.ex
Compiled web/controllers/page_controller.ex
Compiled web/views/layout_view.ex
Compiled lib/test_gettext/endpoint.ex
Generated test_gettext app
Consolidated Plug.Exception
Consolidated Poison.Decoder
Consolidated Phoenix.Param
Consolidated Phoenix.HTML.FormData
Consolidated Phoenix.HTML.Safe
Consolidated Poison.Encoder
Consolidated List.Chars
Consolidated String.Chars
Consolidated Enumerable
Consolidated Collectable
Consolidated IEx.Info
Consolidated Inspect
** (Gettext.PO.SyntaxError) 5: syntax error before:
    lib/gettext/po.ex:97: Gettext.PO.parse_string!/1
    lib/gettext/extractor.ex:151: Gettext.Extractor.merge_or_unchanged/2
    lib/gettext/extractor.ex:175: Gettext.Extractor.tag_files/1
    (elixir) lib/enum.ex:1092: anonymous fn/3 in Enum.map/2
    (stdlib) lists.erl:1262: :lists.foldl/3
    (elixir) lib/enum.ex:1092: Enum.map/2
    lib/gettext/extractor.ex:136: Gettext.Extractor.merge_pot_files/2
    lib/mix/tasks/gettext.extract.ex:59: Mix.Tasks.Gettext.Extract.extract/0
    lib/mix/tasks/gettext.extract.ex:30: Mix.Tasks.Gettext.Extract.run/1
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```

## Workaround

- Clean the gettext output directory: `rm priv/gettext/errors.pot priv/gettext/en/LC_MESSAGES/errors.po`

Running `mix gettext.extract` now works:

```
Compiled web/web.ex
Compiled lib/test_gettext.ex
Compiled web/views/error_helpers.ex
Compiled web/channels/user_socket.ex
Compiled web/gettext.ex
Compiled web/views/error_view.ex
Compiled web/router.ex
Compiled web/views/page_view.ex
Compiled web/views/layout_view.ex
Compiled web/controllers/page_controller.ex
Compiled lib/test_gettext/endpoint.ex
Extracted priv/gettext/default.pot
```

## Additional info

Output of `mix deps`:

```
* fs 0.9.1 (Hex package) (rebar)
  locked at 0.9.2 (fs)
  ok
* gettext 0.9.0 (Hex package) (mix)
  locked at 0.9.0 (gettext)
  ok
* ranch 1.2.1 (Hex package) (rebar)
  locked at 1.2.1 (ranch)
  ok
* poison 2.0.1 (Hex package) (mix)
  locked at 2.0.1 (poison)
  ok
* cowlib 1.0.2 (Hex package) (rebar)
  locked at 1.0.2 (cowlib)
  ok
* cowboy 1.0.4 (Hex package) (rebar)
  locked at 1.0.4 (cowboy)
  ok
* plug 1.1.1 (Hex package) (mix)
  locked at 1.1.1 (plug)
  ok
* phoenix_html 2.5.0 (Hex package) (mix)
  locked at 2.5.0 (phoenix_html)
  ok
* phoenix 1.1.4 (Hex package) (mix)
  locked at 1.1.4 (phoenix)
  ok
* phoenix_live_reload 1.0.3 (Hex package) (mix)
  locked at 1.0.3 (phoenix_live_reload)
  ok
```

**Comment by whatyouhide** [comment] 2016-02-14 21:48
What's your OS? Also, is that the whole output of `mix deps`? Also, did you just do exactly just `mix phoenix.new test_gettext` and `mix gettext.extract`, without doing *anything* between the two (I'm thinking about your editor adding weird characters to `errors.po` in case you opened the file)?

I tried reproducing and it works fine for me, that's why all the questions :).

**Comment by josevalim** [comment] 2016-02-14 21:56
@whatyouhide I think we can at least do the same error reporting as Elixir in that, if it finds a weird character, we tell exactly the codepoint:

```iex
iex(1)> $
** (SyntaxError) iex:1: unexpected token: "$" (column 1, codepoint U+0024)
```

**Comment by nicolashery** [comment] 2016-02-14 22:16
My bad, I double-checked and I actually had the error because my project doesn't use Ecto, so:

```bash
mix phoenix.new test_gettext --no-ecto
cd test_gettext
mix gettext.extract
# ** (Gettext.PO.SyntaxError) 5: syntax error before:
```

```bash
mix phoenix.new test_gettext
cd test_gettext
mix gettext.extract
# Extracted priv/gettext/errors.pot
# Extracted priv/gettext/default.pot
```

Updating the issue title and description accordingly...

**Comment by josevalim** [comment] 2016-02-14 22:18
Ah, thank you. It seems to be a new line thing. The error message from gettext side could be better though. :) We will need to investigate that!

**Comment by nicolashery** [comment] 2016-02-14 22:26
Thanks!

**Comment by josevalim** [comment] 2016-02-16 19:48
Fixed on gettext.

**Closed by josevalim** 2016-02-16 19:48 UTC
