### ISSUE TITLE
Unexpected {error, socket_closed_remotely}

### ISSUE THREAD

**Issue by ThomasArts** [phoenixframework/phoenix#1478] opened 2016-01-18 20:01 UTC
As an experiment I created a super simple phoenix server
https://github.com/ThomasArts/tickets
I wanted to test live_reload and use a ticket.txt file as resource. I know it's ugly, but that's how I did it.

When I run my server, the ticket.txt file is written with a 1 in it. When the browser calls localhost:4000/take, the number if increased. Indeed, both in the file as in another open browser window showing localhost:4000.

My tests uses QuickCheck. Let me know if you need a copy to reproduce this error.
In the Erlang file eqc/ticket_dispenser_eqc.erl (I feel most convenient with Erlang) I write two commands:
reset() ->
  http(get, "http://localhost:4000/reset").

take() ->
  Txt = http(get, "http://localhost:4000/take"),
  list_to_integer(Txt).

http(get, URL) ->
  {ok, {{"HTTP/1.1", 200, "OK"}, _, Txt}} = httpc:request(get, {URL, []}, [], []),
  Txt.

In other words, Erlang is my browser with two windows. I assume that in that context I can perform as many take and reset as I want.

Indeed, any sequence of commands take and reset will behave exactly as expected, returning the right ticket to me.

But, when generating sequences of parallel commands, I get an unexpected error message.
Reason:
  child_failed:
    {3,
     {exception,
        {'EXIT',
           {{badmatch, {error, socket_closed_remotely}},
            [{ticket_dispenser_eqc, http, 2,
                [{file, "ticket_dispenser_eqc.erl"}, {line, 57}]},
             {ticket_dispenser_eqc, take, 0,
                [{file, "ticket_dispenser_eqc.erl"}, {line, 26}]},
             {eqc_run_parallel_commands, run_child, 3,
                [{file, "../src/eqc_run_parallel_commands.hrl"},
                 {line, 75}]}]}}}}

This error is hard to reproduce, next time I run the same parallel sequence, it will just pass.
Debugging is really hard, because the remote (i.e., the Phoenix server as far as I can understand) does in the debug window not show any error:

[info] Sent 200 in 500µs
[info] GET /
[debug] Processing by Tickets.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 200 in 270µs
[debug] Live reload: priv/static/ticket.txt
[debug] Live reload: priv/static/ticket.txt
[info] GET /
[debug] Processing by Tickets.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 200 in 364µs

One typical failure (but there are many different once):
Sequential prefix:

   ticket_dispenser_eqc:take() -> 1
   ticket_dispenser_eqc:take() -> 2
   ticket_dispenser_eqc:take() -> 3
   ticket_dispenser_eqc:reset() -> "reset"
   ticket_dispenser_eqc:take() -> 1
   ticket_dispenser_eqc:take() -> 2
   ticket_dispenser_eqc:take() -> 3
   ticket_dispenser_eqc:take() -> 4
   ticket_dispenser_eqc:take() -> 5
   ticket_dispenser_eqc:take() -> 6
   ticket_dispenser_eqc:reset() -> "reset"
   ticket_dispenser_eqc:take() -> 1
   ticket_dispenser_eqc:take() -> 2
   ticket_dispenser_eqc:take() -> 3
   ticket_dispenser_eqc:take() -> 4
   ticket_dispenser_eqc:take() -> 5
   ticket_dispenser_eqc:take() -> 6
   ticket_dispenser_eqc:take() -> 7
   ticket_dispenser_eqc:take() -> 8
   ticket_dispenser_eqc:take() -> 9

Parallel:

1. ticket_dispenser_eqc:take() -> 10
2. ticket_dispenser_eqc:take() ->
       !!! {'EXIT',
              {{badmatch, {error, socket_closed_remotely}},
               [{ticket_dispenser_eqc, http, 2,
                   [{file, "ticket_dispenser_eqc.erl"}, {line, 57}]},
                {ticket_dispenser_eqc, take, 0,
                   [{file, "ticket_dispenser_eqc.erl"}, {line, 26}]},
                {eqc_run_parallel_commands, run_child, 3,
                   [{file, "../src/eqc_run_parallel_commands.hrl"},
                    {line, 75}]}]}}
3. ticket_dispenser_eqc:take() -> 11
   ticket_dispenser_eqc:take() -> 12
   ticket_dispenser_eqc:take() -> 13

How can one debug this further? Is it possible to see who closes the socket on the remote side?
Regards
Thomas

**Comment by josevalim** [comment] 2016-01-18 20:43
Hi Thomas!

Is your browser open by any chance when you run the tests? If so, I suspect this is happening:

1. You write the ticket to priv/static/ticket.txt
2. Because you have a user connected to the browser, Phoenix live reload mechanism, which reloads pages when they change in development, notices that and asks the browser to reload
3. Because the page is reloaded, the client closes the socket, which leads to a termination on the server

I suspect this to be the case due to these log messages: [debug] Live reload: priv/static/ticket.txt

You may also try disabling live reload all together in your config/dev.exs file.

**Comment by ThomasArts** [comment] 2016-01-19 08:32
> On 18 Jan 2016, at 21:43, José Valim <notifications@github.com> wrote:
> 
> Hi Thomas!
> 
> Is your browser open by any chance when you run the tests? If so, I suspect this is happening:
> 
> You write the ticket to priv/static/ticket.txt
> Because you have a user connected to the browser, Phoenix live reload mechanism, which reloads pages when they change in development, notices that and asks the browser to reload
> Because the page is reloaded, the client closes the socket, which leads to a termination on the server
> I suspect this to be the case due to these log messages: [debug] Live reload: priv/static/ticket.txt
> 
> You may also try disabling live reload all together in your config/dev.exs file.
> 
I closed the browser completely, only having Erlang as "browser" to phoenix.
This still gave me socket closed one out of 20 tests.

I then disabled live-reload completely and still I get socket closed.

Note that I strongly suspect a concurrency issue here. When I test sequentially, everything works fine, but my aim is to see how it behaves if many users at the same time access the service.
I planted a bug that I want to find and do find now and then, but the unexpected socket closed is something I did not anticipated on.

I'll try to dig a bit deeper. It must be possible to get an even simpler example to provoke this behaviour. I'll try to get you one.

Regards
Thomas

**Comment by josevalim** [comment] 2016-01-19 09:14
Sweet! So I am thinking one of two issues here:

1. Phoenix is indeed closing the connection earlier than it should
2. There is a bug in httpc

A quick search for `socket_closed_remotely` reveals different discussions in the Erlang mailing list, including different options to give to httpc to disable pipelining or to make HTTP 1.0 requests as a workaround:

* http://erlang.2086793.n4.nabble.com/confusing-returns-from-httpc-request-4-td2967066.html
* http://erlang.org/pipermail/erlang-questions/2015-March/083804.html
* http://erlang.org/pipermail/erlang-questions/2011-September/061303.html
* http://erlang.org/pipermail/erlang-questions/2015-January/082656.html

Maybe it is worth trying out other HTTP clients or giving those options to httpc to rule out Phoenix/Cowboy closing connections too early? Alternatively, we can try out another webserver and see if the problem persists.

Also, I remember @ericmj ran into issues with httpc, he may have some idea of what is happening. It would be really excellent if we can pinpoint the reason!

**Comment by ThomasArts** [comment] 2016-01-19 10:19
Even within Elixir, I can now provoke an error, running the same static test many times (Client.test).

[error] #PID<0.527.0> running Tickets.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /take
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        :erlang.binary_to_integer("")
        (tickets) lib/tickets.ex:42: Tickets.read/0
        (tickets) web/controllers/page_controller.ex:14: Tickets.PageController.take/2
        (tickets) web/controllers/page_controller.ex:1: Tickets.PageController.action/2
        (tickets) web/controllers/page_controller.ex:1: Tickets.PageController.phoenix_controller_pipeline/2
        (tickets) lib/phoenix/router.ex:261: Tickets.Router.dispatch/2
        (tickets) web/router.ex:1: Tickets.Router.do_call/2
        (tickets) lib/tickets/endpoint.ex:1: Tickets.Endpoint.phoenix_pipeline/1
        (tickets) lib/plug/debugger.ex:93: Tickets.Endpoint."call (overridable 3)"/2
        (tickets) lib/phoenix/endpoint/render_errors.ex:34: Tickets.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4

Note that I did plant a raise condition in the code by overwriting the text file for live_update. Obviously, it is stupid to use a file as a common resource.
What happens is that my file system seems to make the file empty (I guess it is a lock between a write and read that kicks in).

Since the file read returns an empty file, it will not match and the crash closes the socket.??

What surprises me is that I now get this information in my debug output, but that I do not get this if I run from a non elixir client.
(I double checked running the Erlang client... no red text in the debug at all !)
The debug info is helpful and I had wished that even if people attacked my system with Erlang or Java I had seen where the bug in my server was.

I pushed this to github.com/ThomasArts/tickets
The issue is that a utility function in the application:
  def read do
    str = File.read!("priv/static/ticket.txt")
    String.to_integer(str)
  end

crashes because str equals ""
but this is not communicated in the debug output, even though it is called by the page controller:

  def take(conn, params) do
    n = Tickets.read
    Tickets.write(n+1)
    text conn, "#{n}"
  end

/Thomas

**Comment by josevalim** [comment] 2016-01-19 10:31
> Since the file read returns an empty file, it will not match and the crash closes the socket.??

Yes, if the request process terminates abnormally, the connect The wiki is maintained by the community. So if there aren't any up to date instructions, we recommend you to explore the solution yourself and hopefully contribute your findings back!

**Comment by josevalim** [comment] 2016-01-19 10:32
(Sorry for the wrong message. Automation gone wrong. :D)

> Since the file read returns an empty file, it will not match and the crash closes the socket.??

Yes, if the request process terminates abnormally, the connection will be closed. Although I would expect Cowboy to set the proper response headers.

**Comment by josevalim** [comment] 2016-01-19 10:38
> What surprises me is that I now get this information in my debug output, but that I do not get this if I run from a non elixir client.

To be precise, when do you get the debug error message and when you do not? Are you running mix test or an external command? If you can provide steps to reproduce, I will gladly take a deeper look.

**Comment by ThomasArts** [comment] 2016-01-19 11:35
I do this the primitive way. I run all in dev (some other issue with the test environment that I'll figure out later... might become a nice talk for the Elixir conference to just explain how to debug and test simple phoenix servers).

One more thing I found out... the HTTPoison client does pass the tests when I mask the file system read error:
def read do
    case File.read!("priv/static/ticket.txt") do
      <<"">> -> 0
      str -> String.to_integer(str)
    end
  end

In the afternoon, I'll run Elixir QuickCheck with HTTPoison to see if this client is able to detect the raise condition. That's necessary in order to say that it is a good client.

Steps:
mix server.phoenix

In second terminal:
iex -pa _build/dev/lib/certifi/ebin/ -pa _build/dev/lib/connection/ebin/ -pa _build/dev/lib/cowboy/ebin/ -pa _build/dev/lib/cowlib/ebin/ -pa _build/dev/lib/decimal/ebin/ -pa _build/dev/lib/ecto/ebin/ -pa _build/dev/lib/fs/ebin/ -pa _build/dev/lib/gettext/ebin/ -pa _build/dev/lib/hackney/ebin/ -pa _build/dev/lib/httpoison/ebin/ -pa _build/dev/lib/idna/ebin/ -pa _build/dev/lib/mimerl/ebin/ -pa _build/dev/lib/phoenix/ebin/ -pa _build/dev/lib/phoenix_ecto/ebin/ -pa _build/dev/lib/phoenix_html/ebin/ -pa _build/dev/lib/phoenix_live_reload/ebin/ -pa _build/dev/lib/plug/ebin/ -pa _build/dev/lib/poison/ebin/ -pa _build/dev/lib/poolboy/ebin/ -pa _build/dev/lib/postgrex/ebin/ -pa _build/dev/lib/ranch/ebin/ -pa _build/dev/lib/ssl_verify_hostname/ebin/ -pa _build/dev/lib/tickets/ebin/

Yes, this is weird, but I didn't get the ERL_LIBS do it for me.

In Elixir shell: Client.test
Do this a number of times and it will crash the read and show it in the debug output.
(approx 20 times on Mac OSX, Erlang R18).
Note that this error is most likely OS dependent.

The Erlang way of doing it is to run the test in an Erlang shell with
httpc as client. The API is in eqc/ticket_dispenser_eqc.erl


Given that the fix in the read still causes the Erlang client to have a remote socket close, there's something more going on.

Hints on how I should run my tests are welcome.
mix test
does not work out of the box, since it always assumes a database, which I in this case do not have. I guess, I should run "mix test disepenser_eqc" with the QuickCheck stuff installed.
However, I only have live reloading in dev (although I hardly believe that live_reloading has anything to do with it, since I disabled it before and still got the error).

/Thomas

**Comment by ThomasArts** [comment] 2016-01-19 16:18
Getting more and more interesting.

When I use HTTPoison it crashes because of teh READ
When I use httpc I get this strange socket_closed_remotely
When I use ibrowse, my testing works as a charm, no strange unexpected error messages.

I had expected them all to work the same.
/Thomas

**Comment by josevalim** [comment] 2016-01-19 16:21
@ThomasArts do they all write a debug message? Or just HTTPoison?

Can it also be something related to the capability of each tool of doing a concurrent requests? For example, HTTPoison is the only to push load fast enough to reproduce the error?

**Comment by ThomasArts** [comment] 2016-01-19 17:22
> On 19 Jan 2016, at 17:22, José Valim <notifications@github.com> wrote:
> 
> @ThomasArts <https://github.com/ThomasArts> do they all write a debug message? Or just HTTPoison?
> 
Only HTTPoison seems to crash the take and produce a debug message.

> Can it also be something related to the capability of each tool of doing a concurrent requests? For example, HTTPoison is the only to push load fast enough to reproduce the error?
> 
Probably, but that's why I test for concurrency. With ibrowse I do find the concurrency bug rather quickly, thus it definitely is very concurrent as well.

Note that I also need a few concurrent processes, two or tree is sufficient. There's still the possibility of timing involved, but rather when in the code path things happen.

**Comment by ThomasArts** [comment] 2016-01-20 12:55
Solved the issue with httpc. The fact that httpc returns socket_closed_remotely is due to the fact that two different processes share the same profile. By using a different profile for each client process, this error is not triggered.

**Closed** 2016-01-20 13:30 UTC

**Comment by josevalim** [comment] 2016-01-20 13:42
Glad it is all solved!

**Comment by ericmj** [comment] 2016-01-20 13:49
Thanks for investigating @ThomasArts, I never noticed this issue until I got this CI error today: https://travis-ci.org/hexpm/hex/jobs/103599295.

I will try using different profiles for each process.

**Comment by ThomasArts** [comment] 2016-01-20 14:00
Glad this was useful for you Eric.
/Thomas
