### ISSUE TITLE
Weird debug output on fresh project

### ISSUE THREAD

**Issue by GRVYDEV** [phoenixframework/phoenix#5765] opened 2024-03-29 19:27 UTC
### Environment

* Elixir version (elixir -v): 
```
Erlang/OTP 26 [erts-14.2.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]

Elixir 1.16.2 (compiled with Erlang/OTP 26)
```
* Phoenix version (mix deps): 1.7.11
* Operating system: macOS Sonoma 14.1.2

### Actual behavior

Upon running `mix phx.server` on a fresh project I am getting this debug output:

```
[debug] ** (Phoenix.Router.NoRouteError) no route found for GET /assets/777bc9913611365ebcaa.module.wasm (SymWeb.Router)
    (sym_web 0.1.0) /Users/garrettgraves/quantic/sym_umbrella/deps/phoenix/lib/phoenix/router.ex:541: SymWeb.Router.call/2
    (sym_web 0.1.0) lib/sym_web/endpoint.ex:1: SymWeb.Endpoint.plug_builder_call/2
    (sym_web 0.1.0) /Users/garrettgraves/quantic/sym_umbrella/deps/plug/lib/plug/debugger.ex:136: SymWeb.Endpoint."call (overridable 3)"/2
    (sym_web 0.1.0) lib/sym_web/endpoint.ex:1: SymWeb.Endpoint.call/2
    (phoenix 1.7.11) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
    (bandit 1.4.1) lib/bandit/pipeline.ex:150: Bandit.Pipeline.call_plug!/2
    (bandit 1.4.1) lib/bandit/pipeline.ex:36: Bandit.Pipeline.run/4
    (bandit 1.4.1) lib/bandit/http1/handler.ex:12: Bandit.HTTP1.Handler.handle_data/3
    (bandit 1.4.1) lib/bandit/delegating_handler.ex:18: Bandit.DelegatingHandler.handle_data/3
    (bandit 1.4.1) /Users/garrettgraves/quantic/sym_umbrella/deps/thousand_island/lib/thousand_island/handler.ex:379: Bandit.DelegatingHandler.handle_info/2
    (stdlib 5.2) gen_server.erl:1095: :gen_server.try_handle_info/3
    (stdlib 5.2) gen_server.erl:1183: :gen_server.handle_msg/6
    (stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

It _seems_ to be benign but is add none the less.

### Expected behavior

No debug output on fresh install

**Comment by SteffenDE** [comment] 2024-03-29 19:34
Hi! This is most likely another browser tab that is actually requesting the path. Please try closing other browser tabs, windows, etc. Nothing that phoenix generates.

**Comment by josevalim** [comment] 2024-05-02 13:34
Closing this, as the root cause is most likely related to what @SteffenDE suggested. If you have more info, please let us know.

**Closed by josevalim** 2024-05-02 13:34 UTC
