### ISSUE TITLE
Phoenix.Endpoint.Cowboy2Adapter.server_info/2 warning when compiling with Elixir 1.17.0

### ISSUE THREAD

**Issue by krns** [phoenixframework/phoenix#5839] opened 2024-06-12 11:14 UTC
### Environment

* Elixir version (elixir -v): 1.70.0
* Phoenix version (mix deps): 1.7.12
* Operating system: Alpine

### Actual behavior

```
==> phoenix
Compiling 71 files (.ex)
     warning: unknown key .message in expression:
         e.message
     where "e" was given the type:
         # type: %{..., __exception__: true, __struct__: atom()}
         # from: lib/phoenix/endpoint/cowboy2_adapter.ex:149
         rescue e ->
     hint: when you rescue without specifying exception names, the variable is assigned a type of a struct but all of its fields are unknown. If you are trying to access an exception's :message key, either specify the exception names or use `Exception.message/1`.
     │
 149 │     e -> {:error, e.message}
     │                     ~~~~~~~
     │
     └─ lib/phoenix/endpoint/cowboy2_adapter.ex:149:21: Phoenix.Endpoint.Cowboy2Adapter.server_info/2
```

### Expected behavior

Should compile without a warning

**Comment by SteffenDE** [comment] 2024-06-12 11:37
Hi, there. Thanks for reporting. This is a duplicate of https://github.com/phoenixframework/phoenix/issues/5824 and is already fixed on main https://github.com/phoenixframework/phoenix/commit/34d0ffef6aebcb5d4f210978aabca53b0e57f1ae.

**Closed by SteffenDE** 2024-06-12 11:37 UTC
