### ISSUE TITLE
New versions of static files are served on new request

### ISSUE THREAD

**Issue by klirix** [phoenixframework/phoenix#2820] opened 2018-03-23 16:52 UTC
### Environment

* Elixir version (elixir -v): 1.6.1
* Phoenix version (mix deps): 1.3.0
* NodeJS version (node -v): 8.4.0
* NPM version (npm -v): 5.3.0
* Operating system: Win10

### Expected behavior
New versions of static files are served on change in /priv/static, and reloaded via live reload

### Actual behavior
When assets are updated they are successfully compiled and generated into /priv/static folder, the livereload signal is sent to browser, but when it requests the new version of the resource(app.css in my case), the server serves the old version of the file. The version only is updated on page reload/ server reload/ file deletion in priv folder

**Comment by josevalim** [comment] 2018-03-23 17:00
Can you please confirm that the live reload has indeed picked up the change and the browser is trying to reload the CSS? You can do that in a couple different ways:

1. Try refreshing a template and see if it causes a full page reload. If so, it means live reloading is working.
2. Check the logs.

Also please try another browser and let us know which ones you tried. I just checked this in an app I have and code reloading is working just fine (Chrome on Mac). :)

**Comment by klirix** [comment] 2018-03-23 17:07
Yup, the update in a template causes a full page reload, and it is reflected in the logs, and by extension the stylesheets are updated.

**Comment by klirix** [comment] 2018-03-23 17:19
But, if I'm trying to update my css file, the livereload notices the change and notifies browser and upon that the browser requests newly generated app.css?&vsn={timestamp}, but gets the old version instead :(

**Comment by josevalim** [comment] 2018-03-23 17:48
That's so weird. Can you confirm that the vsn is a new one?

**Comment by klirix** [comment] 2018-03-23 17:53
Yup, vsn is always new, also, if I do curl requests updating the vsn manually it doesn't serve new versions

**Comment by josevalim** [comment] 2018-03-23 17:55
Do you have a sample app that reproduces the issue?

**Comment by klirix** [comment] 2018-03-23 18:16
Yup, https://github.com/klirix/phoenix-sample
It might be a windows only issue, as on mac everything works as expected

**Comment by josevalim** [comment] 2018-03-23 18:28
@klirix if it works on Mac I can't reproduce it then. :( Sorry.

@OvermindDL1 can you reproduce it? :S

**Comment by OvermindDL1** [comment] 2018-03-23 18:53
Tried it here on Windows 10 and I was able to edit the css `.container` background color and save and it'd change the color on the page in a second every time.  The `vsn` call changed every time, etc...  I could not reproduce the issue, but I'm using firefox latest.  What browser is @klirix using?

**Comment by OvermindDL1** [comment] 2018-03-23 18:56
Oh wait!  I think I remember experiencing this back when I dev'd on windows too!

I fixed it by telling the anti-virus to ignore my project directory, I'm guessing that it 'delayed' the reading/writing or something on the file so it grabbed the old one or locked it somehow?  Essentially 'yet another' windows filesystem race condition.  Having the AV ignore my project directories fixed a *lot* of bugs.  ^.^;

Try that @klirix perhaps?

**Comment by klirix** [comment] 2018-03-23 19:07
Chrome Win10 / Safari on mac. I added my projects folder to WinDefender exceptions and it had no effect :c 
It really seems to me to be some kind of caching issue on windows, as the mac server works a-ok. However on the server I run on my win machine, responds with the old version of the asset, no matter the svn, or request agent I use, be it curl or browser, until I send a request that hits an action.
Is there any way I can try to dig into the static serving of the file, so that I could trace the request?

**Comment by josevalim** [comment] 2018-03-23 20:12
Maybe #1409?

**Comment by klirix** [comment] 2018-03-26 23:43
@josevalim @OvermindDL1, Thanks for quick response!
I guess it was some kind of weird quirk of my environment, as I was not able to replicate it anywhere else too and ended up using [WSL](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux) on this machine and it worked, which is more beneficial for me anyway. Do I need to close the issue?

**Comment by josevalim** [comment] 2018-03-27 09:09
@klirix we will close the issue then and we can reopen if somebody ends up running into it again. Thanks for reporting back!

**Closed by josevalim** 2018-03-27 09:09 UTC
