### ISSUE TITLE
phoenix dep package.json doesn't have a name, causes npm install to fail.

### ISSUE THREAD

**Issue by sergiotapia** [phoenixframework/phoenix#1622] opened 2016-03-30 07:38 UTC
I was following this guide: https://blog.diacode.com/trello-clone-with-phoenix-and-react-pt-2 and added this file's contents to my own package.json file: https://github.com/bigardone/phoenix-trello/blob/master/package.json

When I try to `npm install` it, I get:

```
sergiotapia at Sergios-iMac in ~/Work/phoenix_trello on master [?]
$ npm install
npm ERR! addLocal Could not install /Users/sergiotapia/Work/phoenix_trello/deps/phoenix
npm ERR! Darwin 15.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1

npm ERR! No name provided in package.json
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>


npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sergiotapia/Work/phoenix_trello/npm-debug.log
```

And when I checked the `deps/phoenix/package.json` file:

```
{
  "repository": {
  },
  "dependencies": {
    "brunch": "^1.8.1",
    "babel-brunch": "^5.1.1",
    "clean-css-brunch": ">= 1.0 < 1.8",
    "css-brunch": ">= 1.0 < 1.8",
    "javascript-brunch": ">= 1.0 < 1.8",
    "uglify-js-brunch": ">= 1.0 < 1.8"
  }
}
```

No name. Is this a bug, or am I misunderstanding?

**Comment by josevalim** [comment] 2016-03-30 07:51
Your lock says you have Phoenix 1.1.4 and Phoenix 1.1.4 *definitely* has the name in there: https://github.com/phoenixframework/phoenix/blob/v1.1.4/package.json

Try running `mix deps.update phoenix phoenix_html` or removing both phoenix and phoenix_html from deps and see if the problem is addressed.

**Comment by sergiotapia** [comment] 2016-03-30 16:29
Thank you Jose, I will try and report back.

**Comment by chrismccord** [comment] 2016-04-09 21:04
Let us know if you have any new info. Closing for now. Thanks!

**Closed by chrismccord** 2016-04-09 21:04 UTC
