### ISSUE TITLE
Cannot render MyApp.ErrorView after updating to 1.3.0-rc.0

### ISSUE THREAD

**Issue by awochna** [phoenixframework/phoenix#2167] opened 2017-03-07 02:31 UTC
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:2:2] [async-threads:10] [kernel-poll:false]

Elixir 1.4.1
```
* Phoenix version (mix deps): `1.3.0-rc.0`
* NodeJS version (node -v): `v6.10.0` (project isn't using node or javascript assets)
* NPM version (npm -v): `3.10.10` (same as above)
* Operating system: Ubuntu 16.04

### Expected behavior

When upgrading from 1.2 to 1.3.0-rc.0, failure to update a reference to a model name in tests (from `MyApp.Model` to `MyApp.Web.Model`) should result in an error about that module not being found.

Of course, updating the model name causes the tests to pass, but that does not expose the error in this case.

### Actual behavior

Instead, tests complain about an `UndefinedFunctionError`, trying to find `MyApp.ErrorView.render`. In this case, all references in tests, supporting files, and source files have been updated to use `MyApp.Web.ErrorView`. The stacktrace looks like this:

```
  3) test registration save service (Garden.RegisterControllerTest)
     test/controllers/registration_controller_test.exs:33
     ** (UndefinedFunctionError) function Garden.ErrorView.render/2 is undefined (module Garden.ErrorView is not available)
     stacktrace:
       Garden.ErrorView.render("500.html", %{conn: %Plug.Conn{adapter: {Plug.Adapters.Test.Conn, :...}, assigns: %{kind: :error, layout: false, reason: %UndefinedFunctionError{arity: 1, exports: nil, function: :new, module: Garden.Service, reason: nil}, stack: [{Garden.Service, :new, [%{"paths" => ["/user"], "token" => "some auth token", "url" => "http://10.0.0.1:9876/"}], []}, {Garden.Web.RegistrationController, :create, 2, [file: 'lib/garden/web/controllers/registration_controller.ex', line: 10]}, {Garden.Web.RegistrationController, :action, 2, [file: 'lib/garden/web/controllers/registration_controller.ex', line: 1]}, {Garden.Web.RegistrationController, :phoenix_controller_pipeline, 2, [file: 'lib/garden/web/controllers/registration_controller.ex', line: 1]}, {Garden.Web.Endpoint, :instrument, 4, [file: 'lib/garden/web/endpoint.ex', line: 1]}, {Phoenix.Router, :__call__, 1, [file: 'lib/phoenix/router.ex', line: 277]}, {Garden.Web.Endpoint, :plug_builder_call, 2, [file: 'lib/garden/web/endpoint.ex', line: 1]}, {Garden.Web.Endpoint, :call, 2, [file: 'lib/garden/web/endpoint.ex', line: 1]}, {Phoenix.ConnTest, :dispatch, 5, [file: 'lib/phoenix/test/conn_test.ex', line: 224]}, {Garden.RegisterControllerTest, :"test registration save service", 1, [file: 'test/controllers/registration_controller_test.exs', line: 34]}, {ExUnit.Runner, :exec_test, 1, [file: 'lib/ex_unit/runner.ex', line: 302]}, {:timer, :tc, 1, [file: 'timer.erl', line: 166]}, {ExUnit.Runner, :"-spawn_test/3-fun-1-", 3, [file: 'lib/ex_unit/runner.ex', line: 250]}]}, before_send: [#Function<1.99940524/1 in Plug.Logger.call/2>], body_params: %{"data" => %{"attributes" => %{"paths" => ["/user"], "token" => "some auth token", "url" => "http://10.0.0.1:9876/"}, "type" => "service registration"}}, cookies: %Plug.Conn.Unfetched{aspect: :cookies}, halted: false, host: "www.example.com", method: "POST", owner: #PID<0.254.0>, params: %{"data" => %{"attributes" => %{"paths" => ["/user"], "token" => "some auth token", "url" => "http://10.0.0.1:9876/"}, "type" => "service registration"}}, path_info: ["registrations"], path_params: %{}, peer: {{127, 0, 0, 1}, 111317}, port: 80, private: %{Garden.Web.Router => {[], %{}}, :phoenix_action => :create, :phoenix_controller => Garden.Web.RegistrationController, :phoenix_endpoint => Garden.Web.Endpoint, :phoenix_format => "html", :phoenix_layout => false, :phoenix_pipelines => [:api], :phoenix_recycled => true, :phoenix_router => Garden.Web.Router, :phoenix_template => "500.html", :phoenix_view => Garden.ErrorView, :plug_session_fetch => #Function<1.131660147/1 in Plug.Session.fetch_session/1>, :plug_skip_csrf_protection => true}, query_params: %{}, query_string: "", remote_ip: {127, 0, 0, 1}, req_cookies: %Plug.Conn.Unfetched{aspect: :cookies}, req_headers: [{"accepts", "application/vnd.api+json"}, {"content-type", "application/vnd.api+json"}], request_path: "/registrations", resp_body: nil, resp_cookies: %{}, resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"}, {"x-request-id", "6g7jqept8mbo0075siiugas07fkcb42q"}], scheme: :http, script_name: [], secret_key_base: "TI6tardVhWwAyKToftNGEYkuhYyGyLFmRZ3ZT7BFhKOptLnP96ddvSb+tEdXW5cZ", state: :unset, status: 500}, kind: :error, reason: %UndefinedFunctionError{arity: 1, exports: nil, function: :new, module: Garden.Service, reason: nil}, stack: [{Garden.Service, :new, [%{"paths" => ["/user"], "token" => "some auth token", "url" => "http://10.0.0.1:9876/"}], []}, {Garden.Web.RegistrationController, :create, 2, [file: 'lib/garden/web/controllers/registration_controller.ex', line: 10]}, {Garden.Web.RegistrationController, :action, 2, [file: 'lib/garden/web/controllers/registration_controller.ex', line: 1]}, {Garden.Web.RegistrationController, :phoenix_controller_pipeline, 2, [file: 'lib/garden/web/controllers/registration_controller.ex', line: 1]}, {Garden.Web.Endpoint, :instrument, 4, [file: 'lib/garden/web/endpoint.ex', line: 1]}, {Phoenix.Router, :__call__, 1, [file: 'lib/phoenix/router.ex', line: 277]}, {Garden.Web.Endpoint, :plug_builder_call, 2, [file: 'lib/garden/web/endpoint.ex', line: 1]}, {Garden.Web.Endpoint, :call, 2, [file: 'lib/garden/web/endpoint.ex', line: 1]}, {Phoenix.ConnTest, :dispatch, 5, [file: 'lib/phoenix/test/conn_test.ex', line: 224]}, {Garden.RegisterControllerTest, :"test registration save service", 1, [file: 'test/controllers/registration_controller_test.exs', line: 34]}, {ExUnit.Runner, :exec_test, 1, [file: 'lib/ex_unit/runner.ex', line: 302]}, {:timer, :tc, 1, [file: 'timer.erl', line: 166]}, {ExUnit.Runner, :"-spawn_test/3-fun-1-", 3, [file: 'lib/ex_unit/runner.ex', line: 250]}], view_module: Garden.ErrorView, view_template: "500.html"})
       (phoenix) lib/phoenix/view.ex:332: Phoenix.View.render_to_iodata/3
       (phoenix) lib/phoenix/controller.ex:740: Phoenix.Controller.do_render/4
       (phoenix) lib/phoenix/endpoint/render_errors.ex:55: Phoenix.Endpoint.RenderErrors.__catch__/5
       (phoenix) lib/phoenix/test/conn_test.ex:224: Phoenix.ConnTest.dispatch/5
       test/controllers/registration_controller_test.exs:34: (test)
```

I could be wrong, but it *seems* like the module name is coming from phoenix somewhere. Running `grep -r "Garden.ErrorView" lib` and `grep -r "Garden.ErrorView test` yield no results.

**Comment by chrismccord** [comment] 2017-03-07 02:34
Have you updated your endpoint config to reference in the new error view module in `config/config.exs`?:

```diff
- config :my_app, MyApp.Endpoint,
+ config :my_app, MyApp.Web.Endpoint,
    ...
-   render_errors: [view: MyApp.ErrorView, accepts: ~w(html json)],
+   render_errors: [view: MyApp.Web.ErrorView, accepts: ~w(html json)],
  ```

**Comment by chrismccord** [comment] 2017-03-07 02:48
I'm positive you missed the step in the upgrade guides to bump your config. Please feel to follow up in this issue if you continue to have problems, but closing since this is not a bug. Thanks!

**Closed by chrismccord** 2017-03-07 02:48 UTC

**Comment by awochna** [comment] 2017-03-07 17:35
Thanks @chrismccord!

That line is different in my `config/config.exs`:

```
config :garden, Garden.Web.Endpoint,
  ...
  render_errors: [accepts: ~w(html json)],
```

Until now, this file hasn't been changed since running `mix phoenix.new` using 1.1.4. I followed the upgrade instructions in [your gist on upgrading from 1.1.x to 1.2.0](https://gist.github.com/chrismccord/29100e16d3990469c47f851e3142f766). Changing the `render_errors` option to match above does now give the correct error.

It should also probably be noted that the `mix phoenix.new` command was run with the `--no-ecto` and `--no-html` option.

I think it's okay to leave this closed for now, because it sounds like I hit a weird edge case across multiple versions of Phoenix. I'll leave it to you to determine if you think there's some unexpected behavior here between the `mix phoenix.new` command and rendering errors and upgrading.

**Comment by chrismccord** [comment] 2017-03-08 06:15
Note that the Phoenix 1.2 to 1.3 upgrade instructions specifically mention updating this value. Glad you got it sorted out!
