### ISSUE TITLE
mix phx.gen.context issues with nesting

### ISSUE THREAD

**Issue by klintmane** [phoenixframework/phoenix#2240] opened 2017-04-07 16:57 UTC
### Environment

* Elixir version (elixir -v): 1.4
* Phoenix version (mix deps): 1.3.0-rc
* NodeJS version (node -v):
* NPM version (npm -v):
* Operating system: Ubuntu 16.10

### Reproducing
![screenshot at 2017-04-07 18-56-05](https://cloud.githubusercontent.com/assets/9338536/24810819/f6cf9388-1bc3-11e7-821f-98bae7954223.png)

### Expected behavior
Running `mix phx.gen.context Site.Blog Post title:string content:string` should create the following directory structure:
![screenshot at 2017-04-07 18-37-45](https://cloud.githubusercontent.com/assets/9338536/24810093/5b4d8232-1bc1-11e7-9aa2-7051d1f88c29.png)
Schema naming should adhere to `snake_case`, like below:
![screenshot at 2017-04-07 18-38-37](https://cloud.githubusercontent.com/assets/9338536/24810150/996c89be-1bc1-11e7-8d48-193655ba4eaa.png)

### Actual behavior
The generated directory structure is mirrored like below:
![screenshot at 2017-04-07 18-34-30](https://cloud.githubusercontent.com/assets/9338536/24810592/161c5452-1bc3-11e7-9610-08d122fe0f9b.png)
The schema name is:
![screenshot at 2017-04-07 18-51-33](https://cloud.githubusercontent.com/assets/9338536/24810635/3e8e057a-1bc3-11e7-9bb7-80f0a761bfba.png)
Related to the above, generated migrations create invalid atoms for table names
![screenshot at 2017-04-07 18-53-52](https://cloud.githubusercontent.com/assets/9338536/24810741/a9bb3610-1bc3-11e7-8433-18d0006173aa.png)

**Comment by lalo2302** [comment] 2017-04-13 16:48
The generator in the image differs from the expected behavior running command

**Comment by lalo2302** [comment] 2017-04-14 03:17
This is because the table name is generated via `Macro.underscore` which according to the docs it converts `"Site.Blog"` to `"site/blog"`.

A short solution could be to trim all `.` characters before underscoring it, or a longer one to create/use another naming solution as the docs suggests:

> This function was designed to underscore language identifiers/tokens, that’s why it belongs to the Macro module. Do not use it as a general mechanism for underscoring strings as it does not support Unicode or characters that are not valid in Elixir identifiers.

I'll submit a PR with the trimming solution because I don't think a new naming system is on the roadmap of v1.3

**Comment by josevalim** [comment] 2017-04-14 09:32
> I'll submit a PR with the . solution because I don't think a new naming system is on the roadmap of v1.3

You can probably underscore and then convert all "/" into "_".

**Comment by chrismccord** [comment] 2017-07-21 16:49
Fixed in master

**Closed by chrismccord** 2017-07-21 16:49 UTC
Labels: kind:bug
