### ISSUE TITLE
Chapter Template Phoenix 1.4.6 Guides fails on the final for render the key.html.eex

### ISSUE THREAD

**Issue by romenigld** [phoenixframework/phoenix#3423] opened 2019-05-23 18:10 UTC
Hello Guys,
I'm reading the guides of Phoenix v1.4.6.
And I'm at the `Templates` Chapter and when I try to do the section `Shared Templates Across Views` which is for move the file `key.html.eex` from the`lib/hello_web/templates/page`  directory into the `lib/hello_web/templates/shared directory`.
and after that put the correct render  `<%= render(HelloWeb.SharedView, "key.html", key: key) %>`.
I can't successfully shows the data.
My browser complains for a:
Internal Server Error
and my terminal for this:
```
[info] GET /testing
[debug] Processing with HelloWeb.PageController.testing/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Converted error Phoenix.Template.UndefinedError to 500 response
[info] Sent 500 in 510µs
[error] #PID<0.457.0> running HelloWeb.Endpoint (connection #PID<0.452.0>, stream id 3) terminated
Server: localhost:4000 (http)
Request: GET /testing
** (exit) an exception was raised:
    ** (Phoenix.Template.UndefinedError) Could not render "key.html" for HelloWeb.PageView, please define a matching clause for render/2 or define a template at "lib/hello_web/templates/page". The following templates were compiled:

* index.html
* test.html
* testing.html

Assigns:

%{__phx_template_not_found__: HelloWeb.PageView, key: :adapter}

Assigned keys: [:__phx_template_not_found__, :key]

        (phoenix) lib/phoenix/template.ex:340: Phoenix.Template.raise_template_not_found/3
        (hello) lib/hello_web/templates/page/testing.html.eex:7: anonymous fn/2 in HelloWeb.PageView."testing.html"/1
        (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
        (hello) lib/hello_web/templates/page/testing.html.eex:6: HelloWeb.PageView."testing.html"/1
        (hello) lib/hello_web/templates/layout/app.html.eex:26: HelloWeb.LayoutView."app.html"/1
        (phoenix) lib/phoenix/view.ex:399: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:729: Phoenix.Controller.__put_render__/5
        (phoenix) lib/phoenix/controller.ex:746: Phoenix.Controller.instrument_render_and_send/4
        (hello) lib/hello_web/controllers/page_controller.ex:1: HelloWeb.PageController.action/2
        (hello) lib/hello_web/controllers/page_controller.ex:1: HelloWeb.PageController.phoenix_controller_pipeline/2
        (hello) lib/hello_web/endpoint.ex:1: HelloWeb.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:275: Phoenix.Router.__call__/1
        (hello) lib/hello_web/endpoint.ex:1: HelloWeb.Endpoint.plug_builder_call/2
        (hello) lib/hello_web/endpoint.ex:1: HelloWeb.Endpoint.call/2
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:33: Phoenix.Endpoint.Cowboy2Handler.init/2
        (cowboy) /Users/romenigld/workspace/phoenix/hello/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
        (cowboy) /Users/romenigld/workspace/phoenix/hello/deps/cowboy/src/cowboy_stream_h.erl:296: :cowboy_stream_h.execute/3
        (cowboy) /Users/romenigld/workspace/phoenix/hello/deps/cowboy/src/cowboy_stream_h.erl:274: :cowboy_stream_h.request_process/3
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

```
My code is at: [hello_repo](https://github.com/romenigld/hello)

So another thing I was thinking and I want to put here:
in the Chapter `Views` we already creates a file `test.html.eex`
So when I try to do the example of the `Templates Chapter` which there you create another file with this same name on the PageController, so for not change the other code I put the action and the file name with 'testing'. 
And I just for this purpose I want to recommend this little change on the Guides.
So everything work's very well, until the final Chapter of the `Templates Chapter` which I post above.

### Environment

* elixir -v
Erlang/OTP 21 [erts-10.1.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
Elixir 1.7.4 (compiled with Erlang/OTP 21)
* Phoenix  version (mix deps):  1.4.6 version
* file_system 0.2.7 (Hex package) (mix)
  locked at 0.2.7 (file_system) e6f7f155
  ok
* connection 1.0.4 (Hex package) (mix)
  locked at 1.0.4 (connection) a1cae722
  ok
* gettext 0.16.1 (Hex package) (mix)
  locked at 0.16.1 (gettext) e2130b25
  ok
* ranch 1.7.1 (Hex package) (rebar3)
  locked at 1.7.1 (ranch) 6b1fab51
  ok
* telemetry 0.4.0 (Hex package) (rebar3)
  locked at 0.4.0 (telemetry) 8339bee3
  ok
* decimal 1.7.0 (Hex package) (mix)
  locked at 1.7.0 (decimal) 30d6b52c
  ok
* jason 1.1.2 (Hex package) (mix)
  locked at 1.1.2 (jason) b03dedea
  ok
* db_connection 2.0.6 (Hex package) (mix)
  locked at 2.0.6 (db_connection) bde2f85d
  ok
* ecto 3.1.4 (Hex package) (mix)
  locked at 3.1.4 (ecto) 69d852da
  ok
* phoenix_pubsub 1.1.2 (Hex package) (mix)
  locked at 1.1.2 (phoenix_pubsub) 496c303b
  ok
* cowlib 2.7.3 (Hex package) (rebar3)
  locked at 2.7.3 (cowlib) a7ffcd09
  ok
* cowboy 2.6.3 (Hex package) (rebar3)
  locked at 2.6.3 (cowboy) 99aa50e9
  ok
* mime 1.3.1 (Hex package) (mix)
  locked at 1.3.1 (mime) 30ce04ab
  ok
* postgrex 0.14.3 (Hex package) (mix)
  locked at 0.14.3 (postgrex) 5754dee2
  ok
* ecto_sql 3.1.2 (Hex package) (mix)
  locked at 3.1.2 (ecto_sql) 529908c0
  ok
* plug_crypto 1.0.0 (Hex package) (mix)
  locked at 1.0.0 (plug_crypto) 18e49317
  ok
* plug 1.8.0 (Hex package) (mix)
  locked at 1.8.0 (plug) 9d2685cb
  ok
* phoenix_html 2.13.2 (Hex package) (mix)
  locked at 2.13.2 (phoenix_html) f5d27c9b
  ok
* plug_cowboy 2.0.2 (Hex package) (mix)
  locked at 2.0.2 (plug_cowboy) 6055f168
  ok
* phoenix 1.4.6 (Hex package) (mix)
  locked at 1.4.6 (phoenix) 8535f4a0
  ok
* phoenix_live_reload 1.2.0 (Hex package) (mix)
  locked at 1.2.0 (phoenix_live_reload) 3bb31a9f
  ok
* phoenix_ecto 4.0.0 (Hex package) (mix)
  locked at 4.0.0 (phoenix_ecto) c43117a1
  ok
* NodeJS version (node -v):  v10.11.0
* NPM version (npm -v): 6.4.1
* Operating system:  Mac OS Mojave 10.14.4

**Comment by michallepicki** [comment] 2019-05-29 10:28
Hi @romenigld ! Love the detailed issue description and that you provided the repo.

Looking at the error stacktrace and your code we can see:
```
        (hello) lib/hello_web/templates/page/testing.html.eex:7: anonymous fn/2 in HelloWeb.PageView."testing.html"/1
```
which in your code is [here](https://github.com/romenigld/hello/commit/4cafbbe96a5c20091d26e1c4b5f63d7e5019a703#diff-890aa4b7774195854be26c6671b4e700R7). This line is in a comment HTML node but since eex doesn't care about HTML syntax it is still being evaluated, just like elixir code in the line above and below.

To have this code commented out you'd have to do something like this:
```
  <!-- <%#= for key <- connection_keys(@conn) do %>
    <%#= render("key.html", key: key) %>
  <%# end %> -->
```
or this:
```
  <%# <%= for key <- connection_keys(@conn) do %>
    <%= render("key.html", key: key) %>
  <% end %> %>
```

The second way is how the `elixir-ls` plugin in Visual Studio Code comments out selected code with `ctrl+/` on my machine.

> So another thing I was thinking and I want to put here:
in the Chapter Views we already creates a file test.html.eex
So when I try to do the example of the Templates Chapter which there you create another file with this same name on the PageController, so for not change the other code I put the action and the file name with 'testing'.
And I just for this purpose I want to recommend this little change on the Guides.
So everything work's very well, until the final Chapter of the Templates Chapter which I post above.

I agree and I think a pull request to change the name would probably get merged. Personally I'd like a more descriptive name, like `conn_introspection` or something similar but shorter. If you don't feel comfortable with doing a PR, you can open a separate issue and I think I could do it.

**Comment by romenigld** [comment] 2019-05-29 15:55
I'm trying to do this comment you put here, and complains for this error:
```
== Compilation error in file lib/hello_web/views/page_view.ex ==
** (EEx.SyntaxError) lib/hello_web/templates/page/testing.html.eex:9: unexpected end of expression <% end %>
```

I'm using Atom app and when I do a comment in any file I press `shift + cmd + /`
And that comment was because of this.
The only way not complains was just using the `#`character.
But when I try do access the testing the same error persists.

I was thinking about how it's the best way for this question of the guides.
Sometimes for do some chapter we need to create another app with the same name in other folder.
And the best way always will be using the git commands like creating and changing for another branch.
Like do in a way organized with best practices. I know there it's not git course but it will help with this thing.
Thank you for your reply @michallepicki!

**Comment by michallepicki** [comment] 2019-05-29 16:11
@romenigld You're right, my second example doesn't work - the first one does, though.
```
  <!-- <%#= for key <- connection_keys(@conn) do %>
    <%#= render("key.html", key: key) %>
  <%# end %> -->
```

**Comment by michallepicki** [comment] 2019-06-03 10:17
@romenigld This can probably be closed now, right? The `key.html.eex` part of the chapter is working fine (it was a mistake in your code) and your naming suggestion is unrelated (you can open a separate issue)

**Comment by romenigld** [comment] 2019-06-03 12:50
hello @michallepicki  that's ok, you can close!

**Comment by romenigld** [comment] 2019-06-05 17:26
So just for explain, the problem was with the comment.
For comment it needs to put like this:
   ```
<%#= for key <- connection_keys(@conn) do %>
    <%#= render("key.html", key: key) %>
   <%# end %>
```

The atom app it's putting a bad comment if puts with the `shift + cmd + /`in files with `*.html.eex`
 It will result: `<!-- my comment -->` and this not work!

**Comment by romenigld** [comment] 2019-06-05 17:40
For this problem for comment on Atom app I need to report a new issue?
How can I switch for the correct comment in these files?

**Closed** 2019-06-06 12:49 UTC

**Comment by the-j0k3r** [comment] 2019-06-11 09:58
@romenigld do you use atom-beautify package? It could be the reason IDK, but reporting this issue on all the wrong repos wont help.

See e.g. https://github.com/Glavin001/atom-beautify/issues/2171 if the issue is same, follwo the instructions in https://github.com/Glavin001/atom-beautify/issues/2171#issuecomment-399856290 to report the issue properly.

If its not atom-beatify check what package you are using that causes the issue and report it to the maintainers of that package.

**Comment by romenigld** [comment] 2019-06-11 12:50
Hello @the-j0k3r I'm not using this atom-beatify.
The packages which I installed for use with elixir was:
* atom-elixir
* language-elixir
thank's for reply.

**Comment by the-j0k3r** [comment] 2019-06-12 06:29
I took a look, Im still unsure which plugin actually causing the issue you reported that in https://github.com/phoenixframework/phoenix/issues/3423#issuecomment-499178755 I dont see that keybinding anywhere in those plugins you mentioned.

Anyway I sure you'll get there eventually.
