### ISSUE TITLE
Phoenix 1.1.3 seams slower compared to version 0.13.1

### ISSUE THREAD

**Issue by adrian-catana** [phoenixframework/phoenix#1658] opened 2016-04-20 16:06 UTC
About benchmarks from https://github.com/mroth/phoenix-showdown I've noticed they are using an older version of phoenix and I wanted to see how it runs with latest version. The problem is 1.1.3 is about 40% slower.

For 0.13.1 I used Elixir 1.0.4 and I get:

````
Adis-Mac-mini:~ adi$ wrk -t4 -c100 -d30S --timeout 2000 "http://127.0.0.1:4000/showdown"
Running 30s test @ http://127.0.0.1:4000/showdown
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     7.59ms    6.04ms  99.35ms   77.06%
    Req/Sec     3.67k   318.18     5.85k    78.42%
  438266 requests in 30.04s, 0.90GB read
Requests/sec:  14590.85
Transfer/sec:     30.60MB
```

For 1.1.3 test I could not use the benchmarker phoenix app from https://github.com/mroth/phoenix-showdown, so I've created a new phoenix app:
- I used --no-ecto and --no-brunch
- I changed the browser pipeline to be the same as on version 0.13.1
- I disabled :info logging in production
- I've added the page controller and all the templates from the old 0.13.1 version and into web/templates/layout/app.html.eex I've replaced `<%= @inner %>` with `<%= render @view_module, @view_template, assigns %>`

You can see the Phoenix 1.1.3 app I used for tests here https://github.com/adrian-catana/benchmarker2 and the test results bellow:

```
Adis-Mac-mini:~ adi$ wrk -t4 -c100 -d30S --timeout 2000 "http://127.0.0.1:4000/showdown"
Running 30s test @ http://127.0.0.1:4000/showdown
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    12.68ms    8.82ms 134.29ms   80.93%
    Req/Sec     2.12k   253.06     3.15k    76.98%
  253493 requests in 30.09s, 573.23MB read
Requests/sec:   8423.20
Transfer/sec:     19.05MB
```

Is this a known issue or there is something wrong with my benchmarks2 app? Maybe I missed some optimizations made in the old 0.13.1 version.

**Comment by chrismccord** [comment] 2016-04-20 16:30
Please remove the Plug.RequestId, and Plug.Logger plugs from your endpoint and try again. I doubt those would be responsible for the slowdown, but that is the first different I noticed in your new app

**Comment by chrismccord** [comment] 2016-04-20 16:31
As a sanity check, your ran both with MIX_ENV=prod, correct?

**Comment by adrian-catana** [comment] 2016-04-20 16:44
with Plug.RequestId and Plug.Logger plugs removed I get:

```
Adis-Mac-mini:~ adi$ wrk -t4 -c100 -d30S --timeout 2000 "http://127.0.0.1:4000/showdown"
Running 30s test @ http://127.0.0.1:4000/showdown
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    11.17ms    8.58ms 148.45ms   85.78%
    Req/Sec     2.42k   344.31     4.88k    77.17%
  289771 requests in 30.09s, 601.66MB read
Requests/sec:   9628.91
Transfer/sec:     19.99MB
```

It is an improvement but still about 35% slower.

About how I've run it:
- for 0.13.1: `MIX_ENV=prod elixir -pa _build/prod/consolidated -S mix phoenix.server`
- for 1.1.3: `MIX_ENV=prod mix phoenix.server`

**Comment by chrismccord** [comment] 2016-04-20 16:46
I see you just updated the layout to remove the static_path call. Let me know what the new runs look like with the updated layout, it's possible our static_path lookup cache is bugged.

**Comment by adrian-catana** [comment] 2016-04-20 17:05
@chrismccord  static_path was already removed when I run the first test from above but I've temporary put them back just to see if they affect performance and they do, with the two static_path calles from layout I get:

```
Adis-Mac-mini:~ adi$ wrk -t4 -c100 -d30S --timeout 2000 "http://127.0.0.1:4000/showdown"
Running 30s test @ http://127.0.0.1:4000/showdown
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    11.87ms    7.96ms 116.59ms   82.52%
    Req/Sec     2.24k   271.97     5.20k    77.01%
  267535 requests in 30.09s, 597.33MB read
Requests/sec:   8890.23
```

So 9628.91 Requests/sec with no static_path vs 8890.23 with static_path calls.

**Comment by chrismccord** [comment] 2016-04-20 17:28
We narrowed this down to a performance issue in Plug.Static. In the 0.13 version we were mounting with `at: "/static"`, but in newer versions we use `at: "/", only: [...]`. The `only` option is supposed to allow us the perf benefits of avoiding unnecessary matches, but it seems whatever work we're doing is costlier than it should be. If you change your `:at` to `at: "/static"`, you should see the same performance across versions. Please let us know if that's not the case, but we're certain on our end .Thanks!

**Comment by josevalim** [comment] 2016-04-20 18:01
Hi @adrian-catana, I reopened because I have a couple more questions. Can you please:

1. Try Plug master?

2. Are you running `mix phoenix.digest` before `mix phoenix.server`? If you digest your assets and generate a manifest, Phoenix will cache the assets lookup

**Comment by chrismccord** [comment] 2016-04-20 18:14
@Gazler can you please remeasure with Plug master? @josevalim pushed a potential optimization

**Comment by Gazler** [comment] 2016-04-20 18:48
@josevalim @chrismccord I set the path back to "/static" and noticed that there was no difference (for the `benchmarker2` app posted) with either `mix phoenix.digest` or using Plug master.

**Comment by josevalim** [comment] 2016-04-20 18:57
Thank you @gazler. Just to be sure, the goal is to check if `only: [...]` is as fast as `at: "/static` in Plug master.

**Comment by adrian-catana** [comment] 2016-04-20 19:03
I can confirm, mix phoenix.digest or using Plug master is not improving performance

**Comment by Gazler** [comment] 2016-04-20 21:20
@josevalim Both of the following configurations are about the same in terms of performance,
Config:

```
  plug Plug.Static,
    at: "/", from: :benchmarker2,
    only: ~w(css images js favicon.ico robots.txt)
```

Results:

```
1.1.3
Running 30s test @ http://127.0.0.1:4000/showdown
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.54ms    2.72ms  32.34ms   89.46%
    Req/Sec    10.64k     1.65k   18.78k    72.80%
  1209115 requests in 30.00s, 2.45GB read
Requests/sec:  40304.31
Transfer/sec:     83.69MB

master:
Running 30s test @ http://127.0.0.1:4000/showdown
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.53ms    2.78ms  36.89ms   89.04%
    Req/Sec    10.68k     1.81k   20.67k    72.83%
  1214368 requests in 30.00s, 2.46GB read
Requests/sec:  40479.39
Transfer/sec:     84.05MB
```

Config:
```
  plug Plug.Static,
    at: "/static", from: :benchmarker2,
    only: ~w(css images js favicon.ico robots.txt)
```

Results:
```
1.1.3:
Running 30s test @ http://127.0.0.1:4000/showdown
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.96ms    3.92ms  69.31ms   89.38%
    Req/Sec    14.23k     3.12k   41.33k    70.19%
  1623176 requests in 30.00s, 3.29GB read
Requests/sec:  54106.33
Transfer/sec:    112.34MB

master:
gazler@gazler-desktop-pc:~$ wrk -t4 -c100 -d30S --timeout 2000 "http://127.0.0.1:4000/showdown"
Running 30s test @ http://127.0.0.1:4000/showdown
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.88ms    3.71ms  59.73ms   89.10%
    Req/Sec    14.54k     3.20k   46.64k    70.82%
  1665076 requests in 30.00s, 3.38GB read
Requests/sec:  55503.07
Transfer/sec:    115.24MB
```

Looks like performance is a little better on master, especially in the second case.

**Comment by josevalim** [comment] 2016-04-20 21:39
@Gazler it should be fixed now in Plug master. The `:only` option was unfortunately not being respected (I was even able to write a test). This solves the Plug issue, although we still need to investigate static_path.

**Comment by adrian-catana** [comment] 2016-04-21 05:28
With at: "/static" and static_path still removed from template I get:

```
Adis-Mac-mini:~ adi$ wrk -t4 -c100 -d30S --timeout 2000 "http://127.0.0.1:4000/showdown"
Running 30s test @ http://127.0.0.1:4000/showdown
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    11.35ms   16.79ms 194.63ms   90.78%
    Req/Sec     3.30k   612.89     6.76k    75.67%
  393890 requests in 30.07s, 817.47MB read
Requests/sec:  13100.73
Transfer/sec:     27.19MB
```

I get similar numbers if I compare plug master vs plug 1.1.3.

This is way better but still about 10% slower compared to 0.13.1.

In case you want downgrade elixir to version 1.0.4 on a mac you can do it like this:

```
brew tap homebrew/versions

brew uninstall --force elixir
brew uninstall --force erlang

# erlang 17 has to be installed before elixir
brew install homebrew/versions/erlang-r17
brew install https://raw.githubusercontent.com/Homebrew/homebrew/8506ced146655c24920f3cc5b20e6bc9e6e703cc/Library/Formula/elixir.rb

when you are done you can remove it with:

brew uninstall --force elixir
brew uninstall --force homebrew/versions/erlang-r17
```
For 0.13.1 I also have to lock deps as bellow or else it will try to install a newer version:

```
 defp deps do
    [{:phoenix, "== 0.13.1"},
     {:cowboy, "== 1.0.0"},
     {:phoenix_live_reload, "== 0.4.0"},
     {:phoenix_html, "== 1.0.0"},
     {:plug, "== 0.12.2"}
   ]
  end
```

**Comment by pillaiindu** [comment] 2016-04-30 23:37
@chrismccord The concurrency of Phoenix is impressive. I also saw the video where you showed how you achieved 1 million concurrent connections. Your work is just amazing. 

But yesterday while playing with TechEmpower performance benchmarks, I noted one thing. In single database query benchmarks, all of the PHP, Ruby, Python and other languages' frameworks outperform Phoenix. I was expecting Phoenix to perform database calls as efficiently as Clojure etc or at least near to expressjs.
What is the reason? I think there is some problem in TechEmpower's implementation, am I right?
[TechEmpower Benchmarks | Single Database Query](https://www.techempower.com/benchmarks/#section=data-r12&hw=peak&test=db&l=16gs90&f=68u1c-3k-4-1kw-mh4w-6bk)

**Comment by jeregrine** [comment] 2016-05-01 06:05
@pillaiindu Chris answered to this here https://www.reddit.com/r/elixir/comments/48ke69/any_reason_why_elixirphoenix_did_so_badly_in/d0ko6ai 

Google is actually very good at context I just had to search 'techempower phoenix elixir' to find that as second result.

**Comment by taggedboy** [comment] 2016-05-01 07:07
Thank You @jeregrine ! :)

**Comment by pillaiindu** [comment] 2016-05-01 07:08
Thank You @jeregrine ! :)

**Comment by chrismccord** [comment] 2016-05-24 16:57
> This is way better but still about 10% slower compared to 0.13.1.

I have been testing locally and static_path as well as Plug.Static can be ruled out as having perf regressions. I also get 10% *worse* performance when downgrading, so I'm putting my money on this being within the margin of error for different environments, vm flags, etc. Thanks for raising this issue. We'll continue to keep a close eye on regressions for reach release.

**Closed by chrismccord** 2016-05-24 16:57 UTC
