### ISSUE TITLE
Broken link in default phoenix page "changelog" button

### ISSUE THREAD

**Issue by marcinkoziej** [phoenixframework/phoenix#5593] opened 2023-10-02 15:22 UTC
### Environment

* Elixir version (elixir -v): 
Erlang/OTP 25 [erts-13.1.4] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Elixir 1.14.3 (compiled with Erlang/OTP 23)

* Phoenix version (mix deps): 
* bcrypt_elixir 3.1.0 (Hex package) (mix)
  locked at 3.1.0 (bcrypt_elixir) 2ad2acb5
  ok
* castore 1.0.3 (Hex package) (mix)
  locked at 1.0.3 (castore) 680ab01e
  ok
* comeonin 5.4.0 (Hex package) (mix)
  locked at 5.4.0 (comeonin) 796393a9
  ok
* cowboy 2.10.0 (Hex package) (rebar3)
  locked at 2.10.0 (cowboy) 3afdccb7
  ok
* cowboy_telemetry 0.4.0 (Hex package) (rebar3)
  locked at 0.4.0 (cowboy_telemetry) 7d98bac1
  ok
* cowlib 2.12.1 (Hex package) (rebar3)
  locked at 2.12.1 (cowlib) 163b73f6
  ok
* db_connection 2.5.0 (Hex package) (mix)
  locked at 2.5.0 (db_connection) c92d5ba2
  ok
* decimal 2.1.1 (Hex package) (mix)
  locked at 2.1.1 (decimal) 53cfe5f4
  ok
* ecto 3.10.3 (Hex package) (mix)
  locked at 3.10.3 (ecto) 44bec74e
  ok
* ecto_sql 3.10.2 (Hex package) (mix)
  locked at 3.10.2 (ecto_sql) 68c018de
  ok
* elixir_make 0.7.7 (Hex package) (mix)
  locked at 0.7.7 (elixir_make) 5bc19fff
  ok
* esbuild 0.7.1 (Hex package) (mix)
  locked at 0.7.1 (esbuild) 66661cdf
  ok
* ex_machina 2.7.0 (Hex package) (mix)
  locked at 2.7.0 (ex_machina) 419aa7a3
  ok
* expo 0.4.1 (Hex package) (mix)
  locked at 0.4.1 (expo) 2ff7ba7a
  ok
* file_system 0.2.10 (Hex package) (mix)
  locked at 0.2.10 (file_system) 41195edb
  ok
* finch 0.16.0 (Hex package) (mix)
  locked at 0.16.0 (finch) f660174c
  ok
* gettext 0.23.1 (Hex package) (mix)
  locked at 0.23.1 (gettext) 19d744a3
  ok
* heroicons 0.5.3 (Hex package) (mix)
  locked at 0.5.3 (heroicons) a210037e
  ok
* hpax 0.1.2 (Hex package) (mix)
  locked at 0.1.2 (hpax) 2c87843d
  ok
* jason 1.4.1 (Hex package) (mix)
  locked at 1.4.1 (jason) fbb01ecd
  ok
* kaffy 0.9.4 (Hex package) (mix)
  locked at 0.9.4 (kaffy) 91736c9d
  ok
* mime 2.0.5 (Hex package) (mix)
  locked at 2.0.5 (mime) da0d64a3
  ok
* mint 1.5.1 (Hex package) (mix)
  locked at 1.5.1 (mint) 4a63e1e7
  ok
* nimble_options 1.0.2 (Hex package) (mix)
  locked at 1.0.2 (nimble_options) fd12a8db
  ok
* nimble_pool 1.0.0 (Hex package) (mix)
  locked at 1.0.0 (nimble_pool) 80be3b88
  ok
* phoenix 1.7.7 (Hex package) (mix)
  locked at 1.7.7 (phoenix) 8966e15c
  ok
* phoenix_ecto 4.4.2 (Hex package) (mix)
  locked at 4.4.2 (phoenix_ecto) 70242edd
  ok
* phoenix_html 3.3.2 (Hex package) (mix)
  locked at 3.3.2 (phoenix_html) 44adaf8e
  ok
* phoenix_live_dashboard 0.7.2 (Hex package) (mix)
  locked at 0.7.2 (phoenix_live_dashboard) 0e5fdf06
  ok
* phoenix_live_reload 1.4.1 (Hex package) (mix)
  locked at 1.4.1 (phoenix_live_reload) 9bffb834
  ok
* phoenix_live_view 0.18.18 (Hex package) (mix)
  locked at 0.18.18 (phoenix_live_view) a5810d04
  ok
* phoenix_pubsub 2.1.3 (Hex package) (mix)
  locked at 2.1.3 (phoenix_pubsub) bba06bc1
  ok
* phoenix_template 1.0.3 (Hex package) (mix)
  locked at 1.0.3 (phoenix_template) 16f4b658
  ok
* phoenix_view 2.0.2 (Hex package) (mix)
  locked at 2.0.2 (phoenix_view) a929e723
  ok
* plug 1.14.2 (Hex package) (mix)
  locked at 1.14.2 (plug) 842fc501
  ok
* plug_cowboy 2.6.1 (Hex package) (mix)
  locked at 2.6.1 (plug_cowboy) de36e1a2
  ok
* plug_crypto 1.2.5 (Hex package) (mix)
  locked at 1.2.5 (plug_crypto) 26549a1d
  ok
* postgrex 0.17.3 (Hex package) (mix)
  locked at 0.17.3 (postgrex) 946cf469
  ok
* ranch 1.8.0 (Hex package) (rebar3)
  locked at 1.8.0 (ranch) 49fbcfd3
  ok
* swoosh 1.12.0 (Hex package) (mix)
  locked at 1.12.0 (swoosh) 87db7ab0
  ok
* tailwind 0.1.10 (Hex package) (mix)
  locked at 0.1.10 (tailwind) e0fc474d
  ok
* telemetry 1.2.1 (Hex package) (rebar3)
  locked at 1.2.1 (telemetry) dad9ce9d
  ok
* telemetry_metrics 0.6.1 (Hex package) (mix)
  locked at 0.6.1 (telemetry_metrics) 7be9e087
  ok
* telemetry_poller 1.0.0 (Hex package) (rebar3)
  locked at 1.0.0 (telemetry_poller) b3a24eaf
  ok
* websock 0.5.3 (Hex package) (mix)
  locked at 0.5.3 (websock) 6105453d
  ok
* websock_adapter 0.5.4 (Hex package) (mix)
  locked at 0.5.4 (websock_adapter) d2c238c7
  ok

* Operating system:
Linux Arch

### Actual behavior
![Screenshot from 2023-10-02 17-20-47](https://github.com/phoenixframework/phoenix/assets/156725/7c7eb7b0-1f2b-43fb-a0f5-62bd5dfc67d5)

### Expected behavior

The link leads to changelog.

**Comment by Gazler** [comment] 2023-10-02 18:21
Not sure where this links to for you, but it links to https://github.com/phoenixframework/phoenix/blob/v1.7.7/CHANGELOG.md for me.

**Comment by Gazler** [comment] 2023-10-02 18:32
Looks like this is a dupe of https://github.com/phoenixframework/phoenix/issues/5307 and if you upgrade phx.new (`mix archive.install hex phx_new`) then ti should resolve your issue.

**Closed by Gazler** 2023-10-02 18:32 UTC
