### ISSUE TITLE
ssl error on phoenix install

### ISSUE THREAD

**Issue by skyeagle** [phoenixframework/phoenix#833] opened 2015-05-01 11:29 UTC
Hello!

I get an error when I follow the first installation instruction:

```bash
mix archive.install https://github.com/phoenixframework/phoenix/releases/download/v0.12.0/phoenix_new-0.12.0.ez
Are you sure you want to install archive https://github.com/phoenixframework/phoenix/releases/download/v0.12.0/phoenix_new-0.12.0.ez? [Yn] y
** (Mix) Could not access url https://github.com/phoenixframework/phoenix/releases/download/v0.12.0/phoenix_new-0.12.0.ez, error: {:failed_connect, [{:to_address, {'github.com', 443}}, {:inet, [:inet], {:eoptions, {{{:badmatch, ""}, [{:ssl_handshake, :dec_hello_extensions, 2, [file: 'ssl_handshake.erl', line: 1737]}, {:ssl_handshake, :decode_handshake, 3, [file: 'ssl_handshake.erl', line: 926]}, {:tls_handshake, :get_tls_handshake_aux, 3, [file: 'tls_handshake.erl', line: 155]}, {:tls_connection, :next_state, 4, [file: 'tls_connection.erl', line: 433]}, {:gen_fsm, :handle_msg, 7, [file: 'gen_fsm.erl', line: 503]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 237]}]}, {:gen_fsm, :sync_send_all_state_event, [#PID<0.88.0>, {:start, :infinity}, :infinity]}}}}]}
```

I tried to google it without a succeed. Any help, please.

**Comment by josevalim** [comment] 2015-05-01 11:31
You can access the page directly, save the file to your computer and then:

    mix archive.install path/to/file/phoenix_new-0.12.0.ez

And it will be installed.

Btw, can you tell us which Erlang version are you running? Just run `iex` and paste the first three lines or so.

/cc @lancehalvorsen should we add a note to the guides telling manual instructions in case it fails?

**Comment by skyeagle** [comment] 2015-05-01 11:33
Thank you!

```
Erlang/OTP 17 [erts-6.2] [source] [64-bit] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.0.4) - press Ctrl+C to exit (type h() ENTER for help)
```

**Comment by lancehalvorsen** [comment] 2015-05-01 21:02
I just created an issue in the guides repo for this.

https://github.com/lancehalvorsen/phoenix-guides/issues/213
/cc @josevalim

**Closed** 2015-05-02 07:01 UTC

**Comment by fokosun** [comment] 2017-08-23 15:31
@josevalim the problem is the download link for phoenix_new-0.12.0.ez. I have also googled to no avail to find it.

This https://github.com/phoenixframework/phoenix/releases/download/v0.12.0/phoenix_new-0.12.0.ez is a 404

If you could paste a link to download this phoenix_new-0.12.0.ez

**Comment by OvermindDL1** [comment] 2017-08-23 17:08
That is an *exceptionally* old version, should not be using it...  o.O

Any issue with grabbing the latest as per the official docs?

**Comment by michalmuskala** [comment] 2017-08-23 18:00
All the archives are stored in the repo: https://github.com/phoenixframework/archives
