### ISSUE TITLE
Ranch undef error occurring after restart.

### ISSUE THREAD

**Issue by dalhorinek** [phoenixframework/phoenix#3175] opened 2018-11-18 22:18 UTC
### Environment

* Elixir version (elixir -v): Elixir 1.7.4 (compiled with Erlang/OTP 21)
* Phoenix version (mix deps): 1.4.0 (phoenix) 56fe9a80
* NodeJS version (node -v): v9.11.2
* NPM version (npm -v): 6.1.0
* Operating system: macOS Mojave 10.14.1 (18B75)

### Expected behavior

Phoenix server runs without Ranch error

### Actual behavior

When I restart Phoenix server, this happens.

```
[error] Ranch listener SitegenWeb.Endpoint.HTTP had connection process started with :cowboy_clear:start_link/4 at #PID<0.432.0> exit with reason: {:undef, [{:cowboy_http, :init, [#PID<0.329.0>, SitegenWeb.Endpoint.HTTP, #Port<0.72>, :ranch_tcp, %{env: %{dispatch: [{:_, [], [{:_, [], Phoenix.Endpoint.Cowboy2Handler, {SitegenWeb.Endpoint, []}}]}]}, stream_handlers: [Plug.Cowboy.Stream]}], []}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}
```

When I remove `_build` directory and run `mix deps.compile && mix compile` and run it again, it works until the server is restarted, however this doesn't apply 100%, sometimes it happens after 2 or more restarts.

Could be related to #3128, however that should be fixed in 1.4.0, right?

This is new project generated using mix phx.new with 1.4.0 phoenix from hex. 
This even happened once on first run with fresh project without any changes yet.

**Comment by josevalim** [comment] 2018-12-04 22:22
Hi @dalhorinek, I cannot reproduce this locally. Can you push a simple project that reproduces this to GitHub? Just in case I am missing something, thanks!

**Comment by dalhorinek** [comment] 2018-12-05 12:33
Hi @josevalim, it seems to be related/the same issue as here https://github.com/benoitc/hackney/issues/528#issuecomment-444172782. It seems that ALE plugin in Vim made some compilation and broke it. I don't get this error after disabling this behaviour.

**Comment by josevalim** [comment] 2018-12-05 22:01
Alright, so we will go ahead and close this. Let us know if there is anything we can do from our side. Thanks!

**Closed by josevalim** 2018-12-05 22:01 UTC
