### ISSUE TITLE
could not compile dependency :phoenix_live_dashboard in master installer

### ISSUE THREAD

**Issue by zhenfeng-zhu** [phoenixframework/phoenix#4941] opened 2022-09-11 00:33 UTC
### Environment

* Elixir version (elixir -v): 
```
Elixir 1.14.0 (compiled with Erlang/OTP 25)
```

* Phoenix version (mix deps):
```
❯ mix deps       
* castore 0.1.18 (Hex package) (mix)
  locked at 0.1.18 (castore) 61bbaf64
  ok
* connection 1.1.0 (Hex package) (mix)
  locked at 1.1.0 (connection) 722c1eb0
  ok
* cowboy 2.9.0 (Hex package) (rebar3)
  locked at 2.9.0 (cowboy) 2c729f93
  ok
* cowboy_telemetry 0.4.0 (Hex package) (rebar3)
  locked at 0.4.0 (cowboy_telemetry) 7d98bac1
  ok
* cowlib 2.11.0 (Hex package) (rebar3)
  locked at 2.11.0 (cowlib) 2b3e9da0
  ok
* db_connection 2.4.2 (Hex package) (mix)
  locked at 2.4.2 (db_connection) 4fe53ca9
  ok
* decimal 2.0.0 (Hex package) (mix)
  locked at 2.0.0 (decimal) 34666e9c
  ok
* ecto 3.8.4 (Hex package) (mix)
  locked at 3.8.4 (ecto) f9244288
  ok
* ecto_sql 3.8.3 (Hex package) (mix)
  locked at 3.8.3 (ecto_sql) 348cb17f
  ok
* esbuild 0.5.0 (Hex package) (mix)
  locked at 0.5.0 (esbuild) f183a0b3
  ok
* file_system 0.2.10 (Hex package) (mix)
  locked at 0.2.10 (file_system) 41195edb
  ok
* gettext 0.20.0 (Hex package) (mix)
  locked at 0.20.0 (gettext) 1c03b177
  ok
* jason 1.3.0 (Hex package) (mix)
  locked at 1.3.0 (jason) 53fc1f51
  ok
* mime 2.0.3 (Hex package) (mix)
  locked at 2.0.3 (mime) 27a30bf0
  ok
* phoenix 1.7.0-dev (../..) (mix)
  ok
* phoenix_ecto (Hex package) (mix)
  locked at 4.4.0 (phoenix_ecto) 09864e55
  the dependency build is outdated, please run "mix deps.compile"
* phoenix_html 3.2.0 (Hex package) (mix)
  locked at 3.2.0 (phoenix_html) 36ec97ba
  ok
* phoenix_live_dashboard (Hex package) (mix)
  locked at 0.6.5 (phoenix_live_dashboard) ef4fa50d
  the dependency build is outdated, please run "mix deps.compile"
* phoenix_live_reload 1.3.3 (Hex package) (mix)
  locked at 1.3.3 (phoenix_live_reload) 76679667
  ok
* phoenix_live_view 0.18.0-dev (https://github.com/phoenixframework/phoenix_live_view.git) (mix)
  locked at 7ddcd58
  ok
* phoenix_pubsub 2.1.1 (Hex package) (mix)
  locked at 2.1.1 (phoenix_pubsub) 81367c6d
  ok
* phoenix_view 1.1.2 (Hex package) (mix)
  locked at 1.1.2 (phoenix_view) 7ae90ad2
  ok
* plug 1.13.6 (Hex package) (mix)
  locked at 1.13.6 (plug) 02b9c6b9
  ok
* plug_cowboy 2.5.2 (Hex package) (mix)
  locked at 2.5.2 (plug_cowboy) ea6e87f7
  ok
* plug_crypto 1.2.3 (Hex package) (mix)
  locked at 1.2.3 (plug_crypto) b5672099
  ok
* postgrex 0.16.4 (Hex package) (mix)
  locked at 0.16.4 (postgrex) 3234d1a7
  ok
* ranch 1.8.0 (Hex package) (rebar3)
  locked at 1.8.0 (ranch) 49fbcfd3
  ok
* swoosh (Hex package) (mix)
  locked at 1.8.0 (swoosh) fd77341d
  the dependency build is outdated, please run "mix deps.compile"
* telemetry 1.1.0 (Hex package) (rebar3)
  locked at 1.1.0 (telemetry) b727b2a1
  ok
* telemetry_metrics 0.6.1 (Hex package) (mix)
  locked at 0.6.1 (telemetry_metrics) 7be9e087
  ok
* telemetry_poller 1.0.0 (Hex package) (rebar3)
  locked at 1.0.0 (telemetry_poller) b3a24eaf
  ok
```

* Operating system:
mac os

### Actual behavior
```
== Compilation error in file lib/phoenix/live_dashboard/pages/metrics_page.ex ==
** (CompileError) lib/phoenix/live_dashboard/pages/metrics_page.ex:18: undefined function assign/2 (expected Phoenix.LiveDashboard.MetricsPage to define such a function or for it to be imported, but none are available)

could not compile dependency :phoenix_live_dashboard, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile phoenix_live_dashboard", update it with "mix deps.update phoenix_live_dashboard" or clean it with "mix deps.clean phoenix_live_dashboard"
```

**Comment by mcrumm** [comment] 2022-09-11 00:42
Yes the master branch is unreleased and we are in the middle of work on the next release, so there will definitely be broken things right now. :)

// Duplicate of #4930

**Closed by mcrumm** 2022-09-11 00:42 UTC

**Comment by zhenfeng-zhu** [comment] 2022-09-11 00:46
thx
