### ISSUE TITLE
function Phoenix.Endpoint.Cowboy2Handler.child_spec/3 is undefined or private

### ISSUE THREAD

**Issue by naddika** [phoenixframework/phoenix#3121] opened 2018-10-24 15:58 UTC
All of a sudden my app has started to crash:

```
        $ mix phx.server
        [................]

        Generated my_app app
        [info] Application my_app exited: MyApp.Application.start(:normal, []) returned an error: shutdown: failed to start child: MyAppWeb.Endpoint
            ** (EXIT) shutdown: failed to start child: Phoenix.Endpoint.Handler
                ** (EXIT) an exception was raised:
                    ** (UndefinedFunctionError) function Phoenix.Endpoint.Cowboy2Handler.child_spec/3 is undefined (module Phoenix.Endpoint.Cowboy2Handler is not available)
                        Phoenix.Endpoint.Cowboy2Handler.child_spec(:http, MyAppWeb.Endpoint, [port: 4000, otp_app: :my_app])
                        (phoenix) lib/phoenix/endpoint/handler.ex:33: anonymous fn/5 in Phoenix.Endpoint.Handler.init/1
                        (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
                        (phoenix) lib/phoenix/endpoint/handler.ex:31: Phoenix.Endpoint.Handler.init/1
                        (stdlib) supervisor.erl:295: :supervisor.init/1
                        (stdlib) gen_server.erl:374: :gen_server.init_it/2
                        (stdlib) gen_server.erl:342: :gen_server.init_it/6
                        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
        ** (Mix) Could not start application my_app: MyApp.Application.start(:normal, []) returned an error: shutdown: failed to start child: MyAppWeb.Endpoint
            ** (EXIT) shutdown: failed to start child: Phoenix.Endpoint.Handler
                ** (EXIT) an exception was raised:
                    ** (UndefinedFunctionError) function Phoenix.Endpoint.Cowboy2Handler.child_spec/3 is undefined (module Phoenix.Endpoint.Cowboy2Handler is not available)
                        Phoenix.Endpoint.Cowboy2Handler.child_spec(:http, MyAppWeb.Endpoint, [port: 4000, otp_app: :my_app])
                        (phoenix) lib/phoenix/endpoint/handler.ex:33: anonymous fn/5 in Phoenix.Endpoint.Handler.init/1
                        (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
                        (phoenix) lib/phoenix/endpoint/handler.ex:31: Phoenix.Endpoint.Handler.init/1
                        (stdlib) supervisor.erl:295: :supervisor.init/1
                        (stdlib) gen_server.erl:374: :gen_server.init_it/2
                        (stdlib) gen_server.erl:342: :gen_server.init_it/6
                        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

```

I'm using and have been using for a while the latest versions of everything: Cowboy - 2.5, Phoenix - 1.3. All has been working fine for over a half a year

This doesn't help

```
      {:phoenix, github: "phoenixframework/phoenix", override: true},
```

Removing _build and recompiling didn't help either

**Comment by chrismccord** [comment] 2018-10-24 16:05
It's not clear where you have phoenix locked at, given you are referencing the master branch on GitHub. Most likely you actually grabbed the 1.4 rc by updating your deps without realizing it. You can either `{:phoenix, "~> 1.3"}` and `mix deps.update phoenix`, or you can use the 1.4rc, which requires you to replace your `:plug` and `:cowboy` deps with `{:plug_cowboy, "~> 2.0"}`. Then` mix deps.get and you should be set. If you indeed are going the 1.4 route, also be sure to checkout the upgrade guides:

https://gist.github.com/chrismccord/bb1f8b136f5a9e4abc0bfc07b832257e

Closing as this goes not appear to be an issue, but if you continue to have problems, please feel free to chime in here. Thanks!

**Comment by naddika** [comment] 2018-10-24 21:48
This doesn't work either, the same error:
```

[
  {:phoenix, "~> 1.4-rc.2", override: true},
  # {:cowboy, "~> 2.4"},
  {:plug_cowboy, "~> 2.0"},


```

**Comment by Gazler** [comment] 2018-10-25 07:07
@naddika Could you please provide your mix.lock file or a sample project? The above configuration is working for me on a new project.

**Comment by naddika** [comment] 2018-10-25 12:08
@Gazler 

I've created a new HelloWorld and the error remains.

mix.exs

        defmodule Hello2.Mixfile do
          use Mix.Project

          def project do
            [
              app: :hello2,
              version: "0.0.1",
              elixir: "~> 1.7",
              elixirc_paths: elixirc_paths(Mix.env),
              compilers: [:phoenix, :gettext] ++ Mix.compilers,
              start_permanent: Mix.env == :prod,
              aliases: aliases(),
              deps: deps()
            ]
          end

          # Configuration for the OTP application.
          #
          # Type `mix help compile.app` for more information.
          def application do
            [
              mod: {Hello2.Application, []},
              extra_applications: [:logger, :runtime_tools]
            ]
          end

          # Specifies which paths to compile per environment.
          defp elixirc_paths(:test), do: ["lib", "test/support"]
          defp elixirc_paths(_),     do: ["lib"]

          # Specifies your project dependencies.
          #
          # Type `mix help deps` for examples and options.
          defp deps do
            [
              {:phoenix, "~> 1.4.0-rc.2"},
              {:phoenix_pubsub, "~> 1.1"},
              {:phoenix_ecto, "~> 3.5"},
              {:ecto, "~> 3.0-rc", override: true},
              {:ecto_sql, "~> 3.0-rc", override: true},
              {:postgrex, ">= 0.0.0-rc"},
              {:phoenix_html, "~> 2.11"},
              {:phoenix_live_reload, "~> 1.2-rc", only: :dev},
              {:gettext, "~> 0.11"},
              {:jason, "~> 1.0"},
              {:plug_cowboy, "~> 2.0"}
            ]
          end

          # Aliases are shortcuts or tasks specific to the current project.
          # For example, to create, migrate and run the seeds file at once:
          #
          #     $ mix ecto.setup
          #
          # See the documentation for `Mix` for more info on aliases.
          defp aliases do
            [
              "ecto.setup": ["ecto.create", "ecto.migrate", "run priv/repo/seeds.exs"],
              "ecto.reset": ["ecto.drop", "ecto.setup"],
              "test": ["ecto.create --quiet", "ecto.migrate", "test"]
            ]
          end
        end


mix.lock

      %{
        "connection": {:hex, :connection, "1.0.4", "a1cae72211f0eef17705aaededacac3eb30e6625b04a6117c1b2db6ace7d5976", [:mix], [], "hexpm"},
        "cowboy": {:hex, :cowboy, "2.5.0", "4ef3ae066ee10fe01ea3272edc8f024347a0d3eb95f6fbb9aed556dacbfc1337", [:rebar3], [{:cowlib, "~> 2.6.0", [hex: :cowlib, repo: "hexpm", optional: false]}, {:ranch, "~> 1.6.2", [hex: :ranch, repo: "hexpm", optional: false]}], "hexpm"},
        "cowlib": {:hex, :cowlib, "2.6.0", "8aa629f81a0fc189f261dc98a42243fa842625feea3c7ec56c48f4ccdb55490f", [:rebar3], [], "hexpm"},
        "db_connection": {:hex, :db_connection, "2.0.0-rc.0", "f6960e86b5e524468ec16fb7277e509c784de565ac520213a1813ad2bf7d802f", [:mix], [{:connection, "~> 1.0.2", [hex: :connection, repo: "hexpm", optional: false]}], "hexpm"},
        "decimal": {:hex, :decimal, "1.5.0", "b0433a36d0e2430e3d50291b1c65f53c37d56f83665b43d79963684865beab68", [:mix], [], "hexpm"},
        "ecto": {:hex, :ecto, "3.0.0-rc.1", "c966a270b289739d6895f61bee339065a3075d1df34ddd369d400cf0c936fd6c", [:mix], [{:decimal, "~> 1.5", [hex: :decimal, repo: "hexpm", optional: false]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: true]}, {:poison, "~> 2.2 or ~> 3.0", [hex: :poison, repo: "hexpm", optional: true]}], "hexpm"},
        "ecto_sql": {:hex, :ecto_sql, "3.0.0-rc.0", "a61da743812a47174e8b79dbe6aa7d4a9f7e6dbf8c90cfd7015f3767738b37ba", [:mix], [{:db_connection, "~> 2.0-rc.0", [hex: :db_connection, repo: "hexpm", optional: false]}, {:ecto, "~> 3.0.0-rc.1", [hex: :ecto, repo: "hexpm", optional: false]}, {:mariaex, "~> 0.9.0-rc.0", [hex: :mariaex, repo: "hexpm", optional: true]}, {:postgrex, "~> 0.14.0-rc.0", [hex: :postgrex, repo: "hexpm", optional: true]}, {:telemetry, "~> 0.2.0", [hex: :telemetry, repo: "hexpm", optional: false]}], "hexpm"},
        "file_system": {:hex, :file_system, "0.2.6", "fd4dc3af89b9ab1dc8ccbcc214a0e60c41f34be251d9307920748a14bf41f1d3", [:mix], [], "hexpm"},
        "gettext": {:hex, :gettext, "0.16.0", "4a7e90408cef5f1bf57c5a39e2db8c372a906031cc9b1466e963101cb927dafc", [:mix], [], "hexpm"},
        "jason": {:hex, :jason, "1.1.2", "b03dedea67a99223a2eaf9f1264ce37154564de899fd3d8b9a21b1a6fd64afe7", [:mix], [{:decimal, "~> 1.0", [hex: :decimal, repo: "hexpm", optional: true]}], "hexpm"},
        "mime": {:hex, :mime, "1.3.0", "5e8d45a39e95c650900d03f897fbf99ae04f60ab1daa4a34c7a20a5151b7a5fe", [:mix], [], "hexpm"},
        "phoenix": {:hex, :phoenix, "1.4.0-rc.2", "5f9d03090a8ea9d03404a5b8610c4b9f43471a45d31cb4282f6789cdaead6f59", [:mix], [{:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: true]}, {:phoenix_pubsub, "~> 1.1", [hex: :phoenix_pubsub, repo: "hexpm", optional: false]}, {:plug, "~> 1.7", [hex: :plug, repo: "hexpm", optional: false]}, {:plug_cowboy, "~> 1.0 or ~> 2.0", [hex: :plug_cowboy, repo: "hexpm", optional: true]}], "hexpm"},
        "phoenix_ecto": {:hex, :phoenix_ecto, "3.5.0", "f72ec302589988698c096da7e8647e917fa2bb2f861c0c3739fc9d95708bacec", [:mix], [{:ecto, "~> 2.2 or ~> 3.0", [hex: :ecto, repo: "hexpm", optional: false]}, {:phoenix_html, "~> 2.9", [hex: :phoenix_html, repo: "hexpm", optional: true]}, {:plug, "~> 1.0", [hex: :plug, repo: "hexpm", optional: false]}], "hexpm"},
        "phoenix_html": {:hex, :phoenix_html, "2.12.0", "1fb3c2e48b4b66d75564d8d63df6d53655469216d6b553e7e14ced2b46f97622", [:mix], [{:plug, "~> 1.5", [hex: :plug, repo: "hexpm", optional: false]}], "hexpm"},
        "phoenix_live_reload": {:hex, :phoenix_live_reload, "1.2.0-rc.0", "e4876fe249fdfbcca372a2c8d512a7c67d893d7a4f1bb66597050aa4d5001a69", [:mix], [{:file_system, "~> 0.2.1 or ~> 0.3", [hex: :file_system, repo: "hexpm", optional: false]}, {:phoenix, "~> 1.4-rc", [hex: :phoenix, repo: "hexpm", optional: false]}], "hexpm"},
        "phoenix_pubsub": {:hex, :phoenix_pubsub, "1.1.1", "6668d787e602981f24f17a5fbb69cc98f8ab085114ebfac6cc36e10a90c8e93c", [:mix], [], "hexpm"},
        "plug": {:hex, :plug, "1.7.1", "8516d565fb84a6a8b2ca722e74e2cd25ca0fc9d64f364ec9dbec09d33eb78ccd", [:mix], [{:mime, "~> 1.0", [hex: :mime, repo: "hexpm", optional: false]}, {:plug_crypto, "~> 1.0", [hex: :plug_crypto, repo: "hexpm", optional: false]}], "hexpm"},
        "plug_cowboy": {:hex, :plug_cowboy, "2.0.0", "ab0c92728f2ba43c544cce85f0f220d8d30fc0c90eaa1e6203683ab039655062", [:mix], [{:cowboy, "~> 2.5", [hex: :cowboy, repo: "hexpm", optional: false]}, {:plug, "~> 1.7", [hex: :plug, repo: "hexpm", optional: false]}], "hexpm"},
        "plug_crypto": {:hex, :plug_crypto, "1.0.0", "18e49317d3fa343f24620ed22795ec29d4a5e602d52d1513ccea0b07d8ea7d4d", [:mix], [], "hexpm"},
        "postgrex": {:hex, :postgrex, "0.14.0-rc.1", "a88cbeab25c5f3fc505fc6590bd30877a5acf11b448aedb23b41cbc063824ceb", [:mix], [{:connection, "~> 1.0", [hex: :connection, repo: "hexpm", optional: false]}, {:db_connection, "~> 2.0-rc.0", [hex: :db_connection, repo: "hexpm", optional: false]}, {:decimal, "~> 1.0", [hex: :decimal, repo: "hexpm", optional: false]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: true]}], "hexpm"},
        "ranch": {:hex, :ranch, "1.6.2", "6db93c78f411ee033dbb18ba8234c5574883acb9a75af0fb90a9b82ea46afa00", [:rebar3], [], "hexpm"},
        "telemetry": {:hex, :telemetry, "0.2.0", "5b40caa3efe4deb30fb12d7cd8ed4f556f6d6bd15c374c2366772161311ce377", [:mix], [], "hexpm"},
      }

**Comment by Gazler** [comment] 2018-10-25 13:16
@naddika Have you changed the `config.exs` of this new project at all? Poison should only be used if this line is missing:

https://github.com/phoenixframework/phoenix/blob/6df2a0f94f8c1a53f5330b98bfb93b9dd29c2df2/installer/templates/phx_single/config/config.exs#L28

**Comment by GildedHonour** [comment] 2018-10-25 13:35
@Gazler no, where in the guides is that mentioned?

Also - if I don't want to use Jason?

**Comment by Gazler** [comment] 2018-10-25 13:38
@GildedHonour It is documented at https://hexdocs.pm/phoenix/1.4.0-rc.2/Phoenix.html#json_library/0

If you don't want to use Jason, configure it to something else.

**Comment by josevalim** [comment] 2018-10-25 13:42
Hi @naddika, there is something suspicious in this hello world. For example, it says `elixir: "~> 1.7"`, but Phoenix does not generate such specification. Is it correct to assume that you have updated only some files from a new project? If so, you can fix this by either:

1. adding `Poison`as a dependency in your mix.exs file: `{:poison, ">= 0.0.0"}`
2. or by adding this to your config/config.exs: `config :phoenix, :json_library, Jason`

The remaining warnings can be fixed by following the instructions in the warning.

**Comment by GildedHonour** [comment] 2018-10-25 13:53
Yes, I have only Elixir 1.7 installed on my machine.

That didn't fix the error:

    1. Added Json to the config
    2. Did this: 
    $ rm -rf _build deps mix.lock && mix deps.get --all
    $ mix phx.server


Still the error remained

**Comment by GildedHonour** [comment] 2018-10-25 13:54
```
  defp deps do
    [
      {:phoenix, "~> 1.4.0-rc.2"},
      {:phoenix_pubsub, "~> 1.1"},
      {:phoenix_ecto, "~> 3.5"},
      {:ecto, "~> 3.0-rc", override: true},
      {:ecto_sql, "~> 3.0-rc", override: true},
      {:postgrex, ">= 0.0.0-rc"},
      {:phoenix_html, "~> 2.11"},
      {:phoenix_live_reload, "~> 1.2-rc", only: :dev},
      {:gettext, "~> 0.11"},
      # {:jason, "~> 1.0"},
      {:plug_cowboy, "~> 2.0"},
    ]
  end

```

**Comment by josevalim** [comment] 2018-10-25 13:55
Can you please add `{:poison, ">= 0.0.0"}` to your deps? You either have to add poison and remove the jason config, or keep the jason dep and the jason config.

**Comment by GildedHonour** [comment] 2018-10-25 13:56
`or keep the jason dep and the jason config.` --> this is what I have.

**Comment by GildedHonour** [comment] 2018-10-25 14:01
Uncommented out jason dependency, ran `rm -rf _build deps mix.lock && mix deps.get --all` -- the error remains.

**Comment by GildedHonour** [comment] 2018-10-25 14:03
Why add `{:poison, ">= 0.0.0"}` if I'm using Jason?

**Comment by josevalim** [comment] 2018-10-25 14:03
@GildedHonour interesting. Can you please push to github a sample app that reproduces the error? Thank you!

**Comment by GildedHonour** [comment] 2018-10-25 14:05
With `{:poison, ">= 0.0.0"}` and Jason in the dependencies and Jason in the config  it works

**Comment by OvermindDL1** [comment] 2018-10-25 15:03
> With {:poison, ">= 0.0.0"} and Jason in the dependencies and Jason in the config it works

That still implies that something is using poison, and based on your dependency list it absolutely shouldn't...  So that sample project would still be useful I'd think?

**Comment by fertapric** [comment] 2018-10-25 23:41
@GildedHonour maybe your endpoint module (the `endpoint.ex` file under your web directory) has `Plug.Parsers` configured with `Poison` as `:json_decoder`?

**Comment by cjbottaro** [comment] 2018-10-30 04:37
I'm having the same issue. Here's how to reproduce...

```sh
$ elixir -v
Erlang/OTP 21 [erts-10.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.7.4 (compiled with Erlang/OTP 21)

$ mix archive
* hex-0.18.1
* phx_new-1.4.0-rc.2
Archives installed at: /Users/cjbottaro/.mix/archives
```

Then...
```
$ mix new umbrella_ex --umbrella
$ cd umbrella_ex/apps/
$ mix phx.new.ecto foo
$ mix phx.new.web foo_web
$ cd ..
$ iex -S mix
Erlang/OTP 21 [erts-10.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

warning: failed to load Poison for Phoenix JSON encoding
(module Poison is not available).

Ensure Poison is loaded from your deps in mix.exs, or
configure an existing encoder in your Mix config using:

    config :phoenix, :json_library, MyJSONLibrary


  (phoenix) lib/phoenix.ex:40: Phoenix.start/2
  (kernel) application_master.erl:277: :application_master.start_it_old/4

==> foo_web
Compiling 11 files (.ex)

== Compilation error in file lib/foo_web/endpoint.ex ==
** (ArgumentError) invalid :json_decoder option. The module Poison is not loaded and could not be found
    (plug) lib/plug/parsers/json.ex:54: Plug.Parsers.JSON.validate_decoder!/1
    (plug) lib/plug/parsers/json.ex:32: Plug.Parsers.JSON.init/1
    (plug) lib/plug/parsers.ex:245: anonymous fn/3 in Plug.Parsers.convert_parsers/2
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    (plug) lib/plug/parsers.ex:228: Plug.Parsers.convert_parsers/2
    (plug) lib/plug/parsers.ex:224: Plug.Parsers.init/1
    (plug) lib/plug/builder.ex:302: Plug.Builder.init_module_plug/4
    (plug) lib/plug/builder.ex:286: anonymous fn/5 in Plug.Builder.compile/3
==> foo
Compiling 3 files (.ex)
Generated foo app
```

Thanks for the help.

**Closed** 2018-10-30 17:54 UTC

**Comment by OvermindDL1** [comment] 2018-10-30 18:09
Is it appropriate to just add it to the template or should the default in Phoenix itself be changed since I keep hearing that Poison's latest API changed things too much to work?

**Comment by chrismccord** [comment] 2018-10-30 18:21
We cannot default to Jason since it would be a breaking change for existing applications. So 1.4 apps are explicitly configured for Jason, allowing us to promote Jason going forward, but existing users  Poison ~> 3.0 will continue to work.

**Comment by OvermindDL1** [comment] 2018-10-30 18:40
> So 1.4 apps are explicitly configured for Jason, allowing us to promote Jason going forward, but existing users Poison ~> 3.0 will continue to work.

I can easily see (as per the forums lately) someone adding Poison v4 to a project after seeing the message that Poison is missing, what about a better error message if the API is not appropriate for the passed in Module atom via a compile-time round-trip JSON test or so using the needed API's?

**Comment by josevalim** [comment] 2018-10-30 18:56
Phoenix does restrict itself to Poison ~> 3.0, so if someone wants to override that, it is their own risk to take.

**Comment by webdeb** [comment] 2018-10-30 19:46
> We cannot default to Jason since it would be a breaking change for existing applications.

I think this what a major release is about. And if someone really depends on a obsolete library, there is still `config :phoenix, :json_library, Poison`.

**Comment by webdeb** [comment] 2018-10-30 19:49
Oh my bad, 1.3 -> 1.4 is actually a minor release.. But it somehow feels like a major. :D
