### ISSUE TITLE
Conn params not merged when specific Plug.Parsers defined

### ISSUE THREAD

**Issue by ngeraedts** [phoenixframework/phoenix#3466] opened 2019-07-04 23:37 UTC
### Environment

* Elixir version: 1.8.1
* Phoenix version: 1.4.9
* NodeJS version: N/A
* NPM version (npm -v): N/A
* Operating system: MacOS & CentOS7

### Expected Behaviour
When specifying only `:multipart` parsers in a Phoenix pipeline, path parameters should still be merged into the connection struct.

### Actual behaviour
I've setup two repositories to demonstrate the issue, and to show (at least to my understanding) that this is a Phoenix issue and not a Plug issue.

https://github.com/ngeraedts/elixir-hello-plug
https://github.com/ngeraedts/elixir-hello-phx

Ultimately, I've specified a `Plug.Parsers` plug with only a multipart decoder. In the Plug example, the path parameters matched by the router are still merged into the `params` field of the connection. In the Phoenix example, they are not and the controller action fails to match on the expected function. 

It's understandable that body parameters are not be merged into `params` if the content type doesn't match the decoder, but the `path_params` field of the connection is appropriately set in both examples.

Commenting out the `Plug.Parsers` line in `HelloWeb.Router` or adding the `:urlencoded` parser allows the tests in `elixir-hello-phx` to pass.

**Comment by javimolla** [comment] 2019-10-08 08:29
If you remove the [line](https://github.com/ngeraedts/elixir-hello-phx/blob/d1233a4bcfee3e799f37a60ace5e8580138eaec7/test/hello_web/controllers/page_controller_test.exs#L23) where you put the content-type header, the test passes:
`|> put_req_header("content-type", "application/x-www-form-urlencoded")`

If you inspect the connection, before getting the response, on the testing methods for both projects, you'll see that without this line they are almost identical

**Comment by ngeraedts** [comment] 2019-10-12 19:04
That somewhat defeats the purpose of the test. The two example repositories are meant to be identical in functionality with Phoenix as an implementation detail.

Both have the same `Plug.Parsers` in their router configuration, [here](https://github.com/ngeraedts/elixir-hello-phx/blob/d1233a4bcfee3e799f37a60ace5e8580138eaec7/lib/hello_web/router.ex#L6) and [here](https://github.com/ngeraedts/elixir-hello-plug/blob/master/lib/hello_plug/router.ex#L7). The only difference is that the Phoenix example has it defined within a pipeline.

**Comment by josevalim** [comment] 2020-02-07 09:00
The issue is that if :pass was triggered, we wouldn't merge params. Fixed in Plug master, thanks!

**Closed by josevalim** 2020-02-07 09:00 UTC

**Comment by ngeraedts** [comment] 2020-02-07 19:12
Thanks José!
