### ISSUE TITLE
Docs: Heroku's Channel demo app error

### ISSUE THREAD

**Issue by gevera** [phoenixframework/phoenix#5332] opened 2023-03-06 17:38 UTC
In the channels docs https://github.com/phoenixframework/phoenix/blob/main/guides/real_time/channels.md
All the way on the bottom there is a link to a demo app that should be running on Heroku. It seems that is not working properly.

![image](https://user-images.githubusercontent.com/1085337/223187856-71eb8dc0-d144-4bba-83b4-21ddf302ad5e.png)

**Comment by YannickFricke** [comment] 2023-03-12 02:37
Duplicate of #5279

**Closed** 2023-03-12 18:03 UTC
