### ISSUE TITLE
new phoenix app in an umbrella fails to compile

### ISSUE THREAD

**Issue by brainlid** [phoenixframework/phoenix#3571] opened 2019-10-10 23:05 UTC
### Environment

* Elixir version (elixir -v): using asdf - latest versions of each
elixir         1.9.1-otp-22
erlang         22.1.3

* Phoenix version (mix deps): 1.4.10
* Operating system: Arch Linux (up to date)

### Expected behavior

Ability to create a new umbrella project with a working phoenix app inside it.

### Actual behavior

Newly created app will not compile by default.

### Steps to recreate

```
mix new my_umb --umbrella
cd my_umb/apps/
mix phx.new broken --no-ecto
```

Now, from the umbrella, try to start the application.

```
$ mix phx.server
...
==> broken
Compiling 12 files (.ex)

== Compilation error in file lib/broken_web/endpoint.ex ==
** (ArgumentError) invalid :json_decoder option. The module Poison is not loaded and could not be found
    (plug) lib/plug/parsers/json.ex:54: Plug.Parsers.JSON.validate_decoder!/1
    (plug) lib/plug/parsers/json.ex:32: Plug.Parsers.JSON.init/1
    (plug) lib/plug/parsers.ex:245: anonymous fn/3 in Plug.Parsers.convert_parsers/2
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    (plug) lib/plug/parsers.ex:228: Plug.Parsers.convert_parsers/2
    (plug) lib/plug/parsers.ex:224: Plug.Parsers.init/1
    (plug) lib/plug/builder.ex:304: Plug.Builder.init_module_plug/4
    (plug) lib/plug/builder.ex:288: anonymous fn/5 in Plug.Builder.compile/3
```

The problem can be fixed by moving the following configuration in `apps/broken/config/config.exs`

```elixir
# Use Jason for JSON parsing in Phoenix
config :phoenix, :json_library, Jason
```

from here into the umbrella root `config/config.exs`. Then it works.

**Comment by Gazler** [comment] 2019-10-11 07:00
This issue is specific to Elixir 1.9 because of https://github.com/elixir-lang/elixir/blob/v1.9/CHANGELOG.md#configuration-overhaul

I guess this applies to all of the config when adding a new application to an umbrella like this. It is not typically an issue when using `mix new` inside of the umbrella as it no longer generates the config.

**Comment by cdvv7788** [comment] 2020-02-07 19:15
Could not reproduce (phoenix ~> 1.4.9 and elixir 1.9.4).

**Comment by dukalskis** [comment] 2020-02-22 10:05
> Could not reproduce (phoenix ~> 1.4.9 and elixir 1.9.4).

Today I reproduced with elixir 1.9.4 and phoenix 1.4.14

**Comment by cdvv7788** [comment] 2020-02-25 13:35
@Gazler confirmed that it is fixed in the latest version?

**Comment by Gazler** [comment] 2020-02-25 14:59
@cdvv7788 Nope - I closed the wrong issue by accident. Sorry!

**Comment by chrismccord** [comment] 2020-04-16 15:52
This is fixed on master. Thanks!

**Closed by chrismccord** 2020-04-16 15:52 UTC
